In [7]:
import yfinance as yf

import os
os.chdir('C:\\Users\\btindol\\OneDrive - Stryker\\Linked In Learn\\Algorithmic Investing\Algorithmic Trading & Quantitative Analysis using Python')  
print(os.getcwd())  # Prints the current working directory

#####################################################################################################################################################
#imports 
#!pip install yfinance 
#!pip install pandas 
#!pip install numpy
#!pip install requests
!pip install datetime
#!pip install yahoofinancials
!pip install stocktrends
from yahoofinancials import YahooFinancials

import pandas as pd
import numpy as np
import requests
import datetime as dt
import os
import json 
from functools import reduce
import statsmodels.api as sm
from stocktrends import Renko
import pandas as pd
import numpy as np
import requests
import datetime as dt


import matplotlib.pyplot as plt
%matplotlib inline

C:\Users\btindol\OneDrive - Stryker\Linked In Learn\Algorithmic Investing\Algorithmic Trading & Quantitative Analysis using Python
Requirement already satisfied: datetime in c:\users\btindol\anaconda3\lib\site-packages (4.3)
Requirement already satisfied: zope.interface in c:\users\btindol\anaconda3\lib\site-packages (from datetime) (5.1.2)
Requirement already satisfied: pytz in c:\users\btindol\anaconda3\lib\site-packages (from datetime) (2020.1)
Requirement already satisfied: setuptools in c:\users\btindol\anaconda3\lib\site-packages (from zope.interface->datetime) (50.3.1.post20201107)

WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the 'c:\users\btindol\anaconda3\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: stocktrends in c:\users\btindol\anaconda3\lib\site-packages (0.1.4)

WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the 'c:\users\btindol\anaconda3\python.exe -m pip install --upgrade pip' command.

In [148]:
# More than 1 ticker
stocks = ['BTC-USD','ETH-USD']
end_date = (dt.date.today()).strftime('%Y-%m-%d')
beg_date = (dt.date.today()-dt.timedelta(1825)).strftime('%Y-%m-%d') # 1825 is 5 years ish 


# Used to make a dataframe of percent change from the daily price data!!!
def get_daily_returns(df):
    daily_return = df.pct_change()
    cols = daily_return.columns.tolist()
    newcols = []
    for j in range(0,len(cols)):
        colz = cols[j] + "_" + "percent_change"

        newcols.append(colz)
    daily_return.columns = newcols               
    return daily_return


def get_stock_data(stocks, begin_date,end_date):
    cl_price = pd.DataFrame()

    # looping over tickers and creating a dataframe with closing prices
    for ticker in stocks:
        cl_price[ticker] = yf.download(ticker,beg_date,end_date)['Adj Close']

    cl_price_plus_ret = get_daily_returns(cl_price)
    final = cl_price.merge(cl_price_plus_ret, on='Date', how='left')
    return final



cl_price2 = get_stock_data(cl_price,beg_date,end_date)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [152]:
cl_price3 = cl_price2
cl_price3

,BTC-USD,ETH-USD,BTC-USD_percent_change,ETH-USD_percent_change
Date,,,,
2016-05-11,452.727997,9.996280,NaN,NaN
2016-05-12,454.765991,10.057800,0.004502,0.006154
2016-05-13,455.670013,10.506600,0.001988,0.044622
2016-05-14,455.670990,10.239700,0.000002,-0.025403
2016-05-15,457.567993,9.962350,0.004163,-0.027086
...,...,...,...,...
2021-05-06,56396.515625,3490.880371,-0.017893,-0.009056
2021-05-07,57356.402344,3484.729004,0.017020,-0.001762
2021-05-08,58803.777344,3902.647705,0.025235,0.119929
2021-05-09,58232.316406,3928.844727,-0.009718,0.006713
2021-05-10,55859.796875,3952.293945,-0.040742,0.005968

In [150]:
#def get_return(df,initial_amount):
pctchg = [col for col in cl_price3.columns if 'percent_change' in col]
pctchg

['BTC-USD_percent_change', 'ETH-USD_percent_change']

In [151]:
colnew = []
for i in range(0,len(pctchg)):
    print(pctchg[i])
    var1 = cl_price3[pctchg[i]].shift(-1)
    colnew.append(var1)
colnew

BTC-USD_percent_change
ETH-USD_percent_change

[Date
 2016-05-11    0.004502
 2016-05-12    0.001988
 2016-05-13    0.000002
 2016-05-14    0.004163
 2016-05-15   -0.007442
                 ...
 2021-05-06    0.017020
 2021-05-07    0.025235
 2021-05-08   -0.009718
 2021-05-09   -0.040742
 2021-05-10         NaN
 Name: BTC-USD_percent_change, Length: 1822, dtype: float64,
 Date
 2016-05-11    0.006154
 2016-05-12    0.044622
 2016-05-13   -0.025403
 2016-05-14   -0.027086
 2016-05-15    0.121352
                 ...
 2021-05-06   -0.001762
 2021-05-07    0.119929
 2021-05-08    0.006713
 2021-05-09    0.005968
 2021-05-10         NaN
 Name: ETH-USD_percent_change, Length: 1822, dtype: float64]

In [153]:
colnew = pd.DataFrame(colnew)
colnew

Date,2016-05-11,2016-05-12,2016-05-13,2016-05-14,2016-05-15,2016-05-16,2016-05-17,2016-05-18,2016-05-19,2016-05-20,...,2021-05-01,2021-05-02,2021-05-03,2021-05-04,2021-05-05,2021-05-06,2021-05-07,2021-05-08,2021-05-09,2021-05-10
BTC-USD_percent_change,0.004502,0.001988,0.000002,0.004163,-0.007442,-0.000837,0.001842,-0.034983,0.009029,0.001157,...,-0.020699,0.010051,-0.06760,0.076696,-0.017893,0.017020,0.025235,-0.009718,-0.040742,NaN
ETH-USD_percent_change,0.006154,0.044622,-0.025403,-0.027086,0.121352,0.091977,0.111470,0.089323,-0.076786,0.027824,...,0.002092,0.162270,-0.05172,0.082724,-0.009056,-0.001762,0.119929,0.006713,0.005968,NaN

In [154]:
colnew = colnew.transpose()
colnew

            BTC-USD_percent_change  ETH-USD_percent_change
Date
2016-05-11                0.004502                0.006154
2016-05-12                0.001988                0.044622
2016-05-13                0.000002               -0.025403
2016-05-14                0.004163               -0.027086
2016-05-15               -0.007442                0.121352
...                            ...                     ...
2021-05-06                0.017020               -0.001762
2021-05-07                0.025235                0.119929
2021-05-08               -0.009718                0.006713
2021-05-09               -0.040742                0.005968
2021-05-10                     NaN                     NaN

[1822 rows x 2 columns]

In [155]:
cols = colnew.columns.tolist()
cols

['BTC-USD_percent_change', 'ETH-USD_percent_change']

In [156]:
cols = colnew.columns.tolist()

newcols = []
for j in range(0,len(cols)):
    colz = cols[j] + "_" + "shift"
           
    newcols.append(colz)
colnew.columns = newcols                         # replace old column to noew

In [157]:
colnew

            BTC-USD_percent_change_shift  ETH-USD_percent_change_shift
Date
2016-05-11                      0.004502                      0.006154
2016-05-12                      0.001988                      0.044622
2016-05-13                      0.000002                     -0.025403
2016-05-14                      0.004163                     -0.027086
2016-05-15                     -0.007442                      0.121352
...                                  ...                           ...
2021-05-06                      0.017020                     -0.001762
2021-05-07                      0.025235                      0.119929
2021-05-08                     -0.009718                      0.006713
2021-05-09                     -0.040742                      0.005968
2021-05-10                           NaN                           NaN

[1822 rows x 2 columns]

In [158]:
final= cl_price3.merge(colnew, on='Date', how='left')
final

,BTC-USD,ETH-USD,BTC-USD_percent_change,ETH-USD_percent_change,BTC-USD_percent_change_shift,ETH-USD_percent_change_shift
Date,,,,,,
2016-05-11,452.727997,9.996280,NaN,NaN,0.004502,0.006154
2016-05-12,454.765991,10.057800,0.004502,0.006154,0.001988,0.044622
2016-05-13,455.670013,10.506600,0.001988,0.044622,0.000002,-0.025403
2016-05-14,455.670990,10.239700,0.000002,-0.025403,0.004163,-0.027086
2016-05-15,457.567993,9.962350,0.004163,-0.027086,-0.007442,0.121352
...,...,...,...,...,...,...
2021-05-06,56396.515625,3490.880371,-0.017893,-0.009056,0.017020,-0.001762
2021-05-07,57356.402344,3484.729004,0.017020,-0.001762,0.025235,0.119929
2021-05-08,58803.777344,3902.647705,0.025235,0.119929,-0.009718,0.006713
2021-05-09,58232.316406,3928.844727,-0.009718,0.006713,-0.040742,0.005968
2021-05-10,55859.796875,3952.293945,-0.040742,0.005968,NaN,NaN

In [159]:
final.fillna(0) # replace all na vlaues with 0

,BTC-USD,ETH-USD,BTC-USD_percent_change,ETH-USD_percent_change,BTC-USD_percent_change_shift,ETH-USD_percent_change_shift
Date,,,,,,
2016-05-11,452.727997,9.996280,0.000000,0.000000,0.004502,0.006154
2016-05-12,454.765991,10.057800,0.004502,0.006154,0.001988,0.044622
2016-05-13,455.670013,10.506600,0.001988,0.044622,0.000002,-0.025403
2016-05-14,455.670990,10.239700,0.000002,-0.025403,0.004163,-0.027086
2016-05-15,457.567993,9.962350,0.004163,-0.027086,-0.007442,0.121352
...,...,...,...,...,...,...
2021-05-06,56396.515625,3490.880371,-0.017893,-0.009056,0.017020,-0.001762
2021-05-07,57356.402344,3484.729004,0.017020,-0.001762,0.025235,0.119929
2021-05-08,58803.777344,3902.647705,0.025235,0.119929,-0.009718,0.006713
2021-05-09,58232.316406,3928.844727,-0.009718,0.006713,-0.040742,0.005968
2021-05-10,55859.796875,3952.293945,-0.040742,0.005968,0.000000,0.000000

In [160]:
final.columns = final.columns.str.replace("-", "_") # replace all the underscores

In [161]:
final

,BTC_USD,ETH_USD,BTC_USD_percent_change,ETH_USD_percent_change,BTC_USD_percent_change_shift,ETH_USD_percent_change_shift
Date,,,,,,
2016-05-11,452.727997,9.996280,NaN,NaN,0.004502,0.006154
2016-05-12,454.765991,10.057800,0.004502,0.006154,0.001988,0.044622
2016-05-13,455.670013,10.506600,0.001988,0.044622,0.000002,-0.025403
2016-05-14,455.670990,10.239700,0.000002,-0.025403,0.004163,-0.027086
2016-05-15,457.567993,9.962350,0.004163,-0.027086,-0.007442,0.121352
...,...,...,...,...,...,...
2021-05-06,56396.515625,3490.880371,-0.017893,-0.009056,0.017020,-0.001762
2021-05-07,57356.402344,3484.729004,0.017020,-0.001762,0.025235,0.119929
2021-05-08,58803.777344,3902.647705,0.025235,0.119929,-0.009718,0.006713
2021-05-09,58232.316406,3928.844727,-0.009718,0.006713,-0.040742,0.005968
2021-05-10,55859.796875,3952.293945,-0.040742,0.005968,NaN,NaN

In [191]:
initial_position= 452.72
shiftval = [col for col in final.columns if 'shift' in col]
shiftval[0]

for i in range(0,len(shiftval)):
    var1 = shiftval[i]
    print(var1)
    #new = [(final.var1.values[0] * initial_position) + initial_position]
#    # print(new)
#new = [(final.BTC_USD_percent_change_shift.values[0] * initial_position) + initial_position]

# for i in range(1, len(final.index)): # starting at second row of the dataframe column 
#     new.append((new[i-1]*final.BTC_USD_percent_change_shift.values[i]) +new[i-1])

BTC_USD_percent_change_shift
ETH_USD_percent_change_shift

In [196]:
shiftval = [col for col in final.columns if 'shift' in col]
shiftval[0]

'BTC_USD_percent_change_shift'

In [201]:
var = final[shiftval[0]] # get the bitcoin shift colum n
var

Date
2016-05-11    0.004502
2016-05-12    0.001988
2016-05-13    0.000002
2016-05-14    0.004163
2016-05-15   -0.007442
                ...
2021-05-06    0.017020
2021-05-07    0.025235
2021-05-08   -0.009718
2021-05-09   -0.040742
2021-05-10         NaN
Name: BTC_USD_percent_change_shift, Length: 1822, dtype: float64

In [214]:
final[shiftval[0]][0]#.values[1]#[0]

0.004501586822668102

In [215]:
#var1 = "BTC_USD_percent_change_shift"
#BTC_USD_percent_change_shift
new = [(final[shiftval[0]][0] * initial_position) + initial_position] # get first value in final for iterate the 0 of this 
new

[454.7579583863583]

In [229]:
new = [(final[shiftval[0]][0] * initial_position) + initial_position] # get first value in final for iterate the 0 of this 
for i in range(1, len(final.index)): # starting at second row of the dataframe column 
    new.append((new[i-1]*final[shiftval].values[i][0]) +new[i-1])
new

[454.7579583863583,
 455.66196463482856,
 455.6629411800789,
 457.5599108459183,
 454.1549722113077,
 453.7749740407662,
 454.61095780914195,
 438.707247032371,
 442.6681756018592,
 443.18015996639303,
 439.31523800182964,
 444.1471533835107,
 445.97310989942633,
 449.591057466769,
 453.3759942719211,
 473.4556261584521,
 530.0306155898579,
 526.223675999534,
 533.8545836879849,
 531.3766001152278,
 536.9104989467135,
 537.9624823176505,
 569.1839156869056,
 572.7168733004289,
 574.9668335572298,
 585.526644587786,
 576.5868000594004,
 581.6347455606818,
 574.6198548229659,
 577.4597704791331,
 606.7162727365326,
 672.7721127650167,
 704.3635347159974,
 685.5469115255956,
 694.4567272875331,
 766.294447607013,
 748.8957681201161,
 756.2136320217526,
 763.7675147035823,
 737.2129910857384,
 666.6402020358495,
 596.105498250724,
 623.9659680386734,
 665.287259625571,
 665.1112373441958,
 629.355887479811,
 655.2634498692996,
 646.9895481675729,
 639.8787118590103,
 673.3250815130264,
 676.2840746556578,
 703.6895964251015,
 658.6523670583967,
 683.6499113427175,
 670.6151684433116,
 677.3190295187919,
 640.5506970594058,
 666.5112370287256,
 650.9485236465604,
 649.3485152879439,
 647.6475565640727,
 664.539286997883,
 654.4564572880436,
 658.06637887411,
 663.2432893825155,
 660.7553572550205,
 679.4469826533777,
 673.0941285613193,
 672.8521284414676,
 665.6732391357714,
 665.0002773901256,
 650.607526251955,
 655.5444507650876,
 661.2732924421739,
 654.0854311269901,
 651.7724837015417,
 654.3404315054871,
 655.023402839949,
 656.9803995216457,
 655.0354265533439,
 624.6699961300966,
 606.2612636839496,
 547.4553566281244,
 566.3449765759896,
 578.2787867737848,
 575.0328724297855,
 587.7676328351001,
 592.6795333761925,
 591.0435759455476,
 587.7906426825615,
 592.0925686466554,
 589.1095891113123,
 587.5486425627097,
 585.5776690771174,
 570.4629458285492,
 567.2299707091171,
 577.4288262015134,
 573.2058783345414,
 574.3078486154806,
 575.6198371593226,
 581.6867465952636,
 581.2977153811563,
 586.742626526704,
 583.4046727928595,
 580.1717587075055,
 577.7507809637375,
 579.6407622276291,
 569.9369541430809,
 573.9018499276486,
 574.0968538073274,
 577.4927899154113,
 575.4618199310008,
 572.2928695595446,
 575.5268212242271,
 598.2014084942834,
 608.6232214741498,
 606.5793122651721,
 610.4251915973537,
 614.5331512610973,
 626.3049159814129,
 622.8500209538392,
 623.4979587274449,
 606.7082772722961,
 608.2322371695417,
 609.230266415397,
 610.673234090942,
 607.1443047265763,
 606.9623011055427,
 605.9733049032532,
 609.8632508398567,
 609.2162285774233,
 608.3012667119257,
 597.1384389892798,
 596.28744083768,
 602.8313315943377,
 602.6143554465261,
 600.8153759931513,
 608.0322895295329,
 606.1553085242866,
 604.7173456431498,
 605.6822944186495,
 609.7242152098383,
 613.9721260147725,
 610.8812382292658,
 612.122183106145,
 610.1932010663177,
 612.5001671521077,
 613.0101679091017,
 617.11007107453,
 619.0970354885966,
 616.741120072133,
 618.9830848646967,
 641.0606978164,
 636.1807791322566,
 636.7747627807805,
 640.3666793137936,
 638.6347152782239,
 641.6196479040678,
 639.1817026865749,
 637.9487532739329,
 630.5088822500812,
 630.8458513955293,
 632.8168248811215,
 657.2823961403155,
 657.0593776187674,
 653.7494385267922,
 657.5763972947484,
 678.2920347926074,
 688.3008301656548,
 689.6388192267874,
 714.4663836034696,
 701.8516161957913,
 700.9596031436769,
 729.7801389808742,
 740.8158937528185,
 688.6878472551832,
 703.2225636591231,
 703.4056048594852,
 711.5094045854169,
 703.118561589961,
 709.8354839581648,
 723.2602346169282,
 715.5213576442356,
 716.398356313126,
 705.04156229013,
 702.0186054336007,
 705.0085428538526,
 711.6064487696702,
 744.1848527983617,
 740.9639013923244,
 751.571746242382,
 751.6027515540806,
 731.0130883935165,
 739.234928026584,
 751.3337133376098,
 744.5808418973776,
 740.2759252634544,
 741.6358865927198,
 735.3690295167701,
 732.0220427393598,
 735.7999911425641,
 735.5910104589897,
 745.6778073839085,
 756.7606194301039,
 777.9302284012183,
 771.1414078889578,
 773.8583398776594,
 758.6866108001021,
 764.2105000427716,
 768.1184510324285,
 770.7963822451943,
 772.7803559894319,
 774.6363412717958,
 769.7174218117166,
 780.0731959190281,
 780.5422428095856,
 781.4672142638993,
 778.0742688256446,
 784.8931181043533,
 790.8150105706177,
 790.516065655855,
 792.6999870401012,
 800.8618301743505,
 834.2662694166796,
 864.5247071009358,
 921.9677231917444,
 898.8061450121553,
 896.1671535412471,
 907.5939536518774,
 933.1815143696426,
 975.9037821863203,
 973.479813772723,
 961.2209971087965,
 963.7259577440944,
 998.3073781494052,
 1021.7319521717285,
 1043.8215278027485,
 1154.7095837294423,
 1013.362104899155,
 902.1850526124363,
 908.5689730502713,
 911.1828795150612,
 902.8120556972375,
 907.6629831942612,
 777.7432810198546,
 804.8197680740093,
 823.9694542288578,
 818.3975311666868,
 821.7834576859547,
 831.51930866153,
 907.921950787838,
 886.602320052639,
 899.0571171414946,
 895.0101915558977,
 921.7727193120656,
 924.6566405385768,
 920.995755497258,
 892.671243613159,
 901.5260676706863,
 917.5697906227258,
 919.7337538634181,
 921.5737482173074,
 919.4797300301714,
 920.3657617426273,
 970.385874283309,
 989.0055405035313,
 1011.7821157181708,
 1029.891842215477,
 1042.8816029992888,
 1027.3218192528745,
 1038.1316869015977,
 1061.331228277794,
 1063.0511685999688,
 994.3654311782204,
 988.6565476446881,
 1004.4322699595854,
 999.1633810954128,
 990.6245304604512,
 1004.5322437795897,
 1007.4621847010234,
 1027.421793072879,
 1046.191481057186,
 1054.4014190450148,
 1047.8514859146205,
 1079.9609040868324,
 1115.2803485650934,
 1117.4202033449178,
 1166.6993621768984,
 1173.6593222442825,
 1143.8197614383473,
 1165.1793694947323,
 1179.9491281336152,
 1179.9491281336152,
 1222.4784061951927,
 1250.9879123701544,
 1274.9674692650658,
 1255.1278538908468,
 1267.0976131606703,
 1272.807473239453,
 1223.5184268868127,
 1149.9796868093836,
 1188.4689971702728,
 1116.7002453590987,
 1175.8091866129223,
 1221.3584308611998,
 1231.898283748202,
 1239.978097081422,
 1249.5879126856244,
 1187.7890775397182,
 1100.2105463980408,
 973.8007919896962,
 1036.7216776282519,
 1054.2113589256655,
 1120.520246242146,
 1049.1214830126974,
 1038.5716205368792,
 937.5034595113685,
 972.7618088774046,
 966.7078997001089,
 1045.751547421904,
 1047.1315279288015,
 1039.9516010437767,
 1026.411923215863,
 1071.7711073447917,
 1080.4809144326423,
 1102.1505756060128,
 1143.7898547400548,
 1133.2299826754206,
 1124.760161582843,
 1182.6591632714858,
 1176.8792360709906,
 1175.9291796105588,
 1187.8490130044584,
 1187.1090358410074,
 1204.9887248977786,
 1200.3487922089082,
 1169.2593755506844,
 1167.5194160508775,
 1172.4993085550254,
 1182.9190463762347,
 1193.8889453778586,
 1211.6486414369936,
 1210.268660930096,
 1229.0582460238788,
 1222.028462971095,
 1231.6882044512213,
 1207.1886372104996,
 1250.1279422090668,
 1265.4676370696839,
 1281.05732751439,
 1317.7067045554681,
 1316.4567266350232,
 1321.7666914337885,
 1347.8662059990484,
 1421.5748649500379,
 1452.7942841947142,
 1490.0636454016067,
 1537.6428830890443,
 1555.4224762576548,
 1578.772161466092,
 1596.681757221155,
 1723.3195349454556,
 1755.3289792976634,
 1787.098437654598,
 1848.5372938075948,
 1724.2095338729914,
 1804.878152891365,
 1808.878082236789,
 1738.3993467013242,
 1734.4193144653761,
 1839.0574807898454,
 1888.616663972363,
 1987.6748507363454,
 2084.693156540508,
 2041.1638961425745,
 2173.3615121815733,
 2320.3789348035352,
 2443.596728992962,
 2304.939266122914,
 2202.381019113529,
 2038.8339812434015,
 2155.7619695434955,
 2255.5702651279016,
 2175.431543975998,
 2286.3695257786158,
 2407.83735087942,
 2488.5060919659495,
 2515.3056674075524,
 2511.7656908750423,
 2686.7625997373398,
 2863.1493766271947,
 2732.111652209296,
 2805.5705597125093,
 2823.7601798181095,
 2947.6578936380906,
 2958.0578564179805,
 2659.582904057039,
 2716.9720270568437,
 2506.3258455579803,
 2464.5365446598535,
 2518.5155716454447,
 2655.8329702957035,
 2548.245026974403,
 2589.554355881984,
 2721.7419623321666,
 2689.0525983494044,
 2705.362124711773,
 2744.8614269978348,
 2608.673891202228,
 2589.3641736944787,
 2478.4061727142284,
 2552.4048656045716,
 2574.744558887837,
 2539.2752147136475,
 2480.7962672144545,
 2434.5070458027258,
 2506.425697309828,
 2564.014767949642,
 2601.5939381372073,
 2601.9440296094567,
 2608.5139819174833,
 2518.615423397293,
 2571.2946686546716,
 2518.3954565796525,
 2372.5181505374717,
 2337.748745171469,
 2398.797715633265,
 2357.8582532392534,
 2233.300638966349,
 1998.8246782003464,
 1929.7858586365192,
 2228.370550269969,
 2318.8389229437375,
 2273.3897745836207,
 2817.55032857115,
 2667.712887402497,
 2810.0704802261125,
 2730.351673531858,
 2754.811446553628,
 2576.4344704435644,
 2529.4052718683847,
 2671.732835925552,
 2808.9603924127787,
 2726.4017921305135,
 2757.131229795828,
 2875.2892989068914,
 2718.211995388473,
 2710.6220415664584,
 2804.6804387168177,
 2895.838740609957,
 3252.8524538666757,
 3213.8831715152405,
 3378.8802570139783,
 3419.879532804574,
 3342.4109305034335,
 3381.2203035701245,
 3650.555633933318,
 3884.6413428036503,
 4073.188061150834,
 4325.053485257934,
 4181.856307655332,
 4376.552575580267,
 4331.613427977144,
 4160.546625474871,
 4193.626119285146,
 4087.5877091398347,
 4001.6693049237488,
 4100.447589405351,
 4151.446688559507,
 4334.6036095337095,
 4371.522879268352,
 4352.323023101267,
 4382.802465182493,
 4382.582742501165,
 4578.939137351692,
 4565.219164856932,
 4703.307057709715,
 4891.923354905986,
 4578.689141767602,
 4582.879009164219,
 4236.235229920941,
 4376.452479692107,
 4597.038915294259,
 4599.798632171741,
 4228.6753048653745,
 4225.985410973292,
 4122.867115262833,
 4161.196516338978,
 4130.737093435385,
 3882.5215072014594,
 3154.894223259055,
 3637.4557676725303,
 3624.9760076457123,
 3582.816596097704,
 4065.1281449270905,
 3924.9006414307955,
 3905.8809578624,
 3630.9759016638486,
 3630.635819780415,
 3792.332914741916,
 3682.7750355143517,
 3926.0007196553133,
 3892.2813445697466,
 4200.595722736879,
 4174.65623952452,
 4162.996289235369,
 4338.633323509269,
 4403.6624482751695,
 4409.24193956303,
 4317.403718039337,
 4229.285157374217,
 4328.333700753853,
 4370.732854160821,
 4426.811941707285,
 4610.39854259164,
 4771.935728268395,
 4781.90576700182,
 4826.394727244533,
 5446.813943968023,
 5647.110210631077,
 5831.687028399285,
 5678.08964388048,
 5725.488708969229,
 5605.410751895983,
 5590.591189449332,
 5708.419186265778,
 6011.344011196242,
 6031.49355761929,
 6008.313791284413,
 5930.215073160485,
 5526.542516114781,
 5750.698224606955,
 5904.7257773085375,
 5780.797790585795,
 5752.98822321902,
 6153.74139823881,
 6130.421497660508,
 6468.2856468305345,
 6767.190523237941,
 7078.374967895846,
 7207.63245032236,
 7379.819838499407,
 7407.2793143939325,
 7022.635718096502,
 7144.253687029548,
 7459.55817609867,
 7143.453896469514,
 6618.02323624734,
 6357.487799271342,
 5949.964724303516,
 6559.374369874586,
 6635.632788474234,
 7315.41081996748,
 7871.550898677337,
 7708.854065515793,
 7790.01229990906,
 8036.348280672379,
 8200.494795258062,
 8071.117197765755,
 8253.404016921897,
 8038.628025559314,
 8253.544639437949,
 8790.764642194945,
 9330.384993177295,
 9818.176181542694,
 10058.622129628542,
 9888.435682669457,
 10233.41884671452,
 10975.40574029066,
 11074.403991589903,
 11323.000186335152,
 11656.994286678051,
 11916.48970296243,
 14291.247560031576,
 17899.383044835045,
 16569.107714634978,
 15177.93209298748,
 15455.12739193441,
 16936.501615630266,
 17415.09277119214,
 16407.90939016009,
 16563.707419400554,
 17706.587622239913,
 19497.05599548531,
 19140.462684958864,
 19113.861592339395,
 17776.385217463263,
 16624.305958365632,
 15802.621253818119,
 13831.555484699684,
 14698.940553872966,
 13925.553824317145,
 14026.351848512779,
 16099.515423555062,
 15838.220234374292,
 14606.241995983717,
 14655.941313409658,
 12951.971412259056,
 14156.150337007986,
 13656.95895939003,
 14981.834970900925,
 15200.731494947351,
 15598.924656593355,
 17429.192131516666,
 17526.690409311374,
 16477.308554921303,
 15169.83165013585,
 14595.142582668264,
 14973.035321650043,
 13405.563009412035,
 13980.352661040408,
 14359.946541848289,
 13771.756736294647,
 13819.555696663412,
 11490.297035898462,
 11188.401977934489,
 11474.697702069408,
 11607.195361636577,
 12898.972348432191,
 11599.894709344979,
 10931.20730225993,
 10868.208415069505,
 11359.199742220293,
 11259.201508584694,
 11171.203062985367,
 11440.498110856985,
 11786.091615683514,
 11296.200855029867,
 10106.121290605457,
 10220.919067510074,
 9170.37805390784,
 8830.594016775629,
 9174.748093903145,
 8276.863563471004,
 6955.147164117609,
 7753.863036104321,
 7621.165184760831,
 8265.44384331344,
 8736.826141837248,
 8621.74809644578,
 8129.826609944035,
 8926.41263673974,
 8598.157692833134,
 9494.462173050213,
 10166.220814947605,
 10233.719622651633,
 11112.503904532225,
 10551.613421452052,
 11225.10152498781,
 11403.498764411817,
 10690.211559198142,
 10004.823275241648,
 10300.917654418554,
 9812.896977919321,
 9664.559754391514,
 10366.517081610657,
 10725.410156201671,
 10397.716725814014,
 10950.80656543441,
 11086.20456439511,
 11489.497245338427,
 11512.396254913829,
 11573.095378039687,
 10779.709978301997,
 9965.394284213608,
 9394.843815516997,
 9337.384869531792,
 8865.843394132176,
 9578.460689304113,
 9204.957521222648,
 9194.68719482474,
 8269.66349534019,
 8300.713728120243,
 8338.202323735839,
 7916.740041864551,
 8223.534427349518,
 8630.497941888894,
 8913.312282206325,
 8929.122549809454,
 8728.315549980467,
 8879.463270738775,
 8667.967006599483,
 8495.630206999132,
 8209.255382698935,
 7832.901679031706,
 7954.339475366062,
 7165.573622935142,
 6890.398307838556,
 6973.406607208606,
 6844.109086426827,
 7083.674678969485,
 7455.978161210897,
 6853.718779962872,
 6811.3498994586635,
 6636.202602627813,
 6910.9677687192525,
 7023.395958573901,
 6770.610384704662,
 6834.63903886158,
 6968.196738298001,
 7889.110647096464,
 7895.820489511603,
 7986.099168270493,
 8328.963229122299,
 8058.527576398275,
 7901.950264048035,
 8163.2757261315655,
 8294.16306258091,
 8845.673828531493,
 8895.422949765203,
 8802.304477418304,
 8930.72213092952,
 9697.328706812175,
 8845.583986368461,
 9281.34582034059,
 8986.891060639016,
 9348.31534051893,
 9418.913702847562,
 9240.386582905257,
 9118.84869068274,
 9235.756781873359,
 9743.68823948193,
 9700.588414857837,
 9857.976259765865,
 9654.629265740725,
 9372.844204117162,
 9234.657191921468,
 9325.014970845636,
 9043.780680743268,
 8441.341126896554,
 8504.739421094373,
 8723.786333109352,
 8716.636068786307,
 8510.229558491828,
 8368.682254089688,
 8094.176849034841,
 8250.823984370481,
 8247.034012253882,
 8513.099624982598,
 8418.841524328544,
 8041.637738020887,
 7557.6863255798535,
 7587.205823679988,
 7480.0080101862,
 7355.74995116884,
 7368.090065224858,
 7135.864186783813,
 7472.457850583138,
 7406.389193398243,
 7494.03754752532,
 7541.316985820902,
 7643.315184129213,
 7720.1136322523025,
 7514.337481916922,
 7633.624925610012,
 7653.844783291085,
 7678.104608672846,
 7624.785238003865,
 7531.846938255654,
 6785.900153689353,
 6906.797920500267,
 6582.243594819853,
 6349.78773997235,
 6675.232186648456,
 6456.466031392953,
 6550.044456552766,
 6499.155218739275,
 6734.700862758878,
 6769.820359597132,
 6776.43010612411,
 6729.621362639197,
 6083.582481272837,
 6162.371128616136,
 6173.120938731963,
 6249.06979248725,
 6093.5622854587655,
 6157.021125462107,
 5903.335665144672,
 6218.189966853383,
 6403.88688202374,
 6385.707027370644,
 6614.063345257187,
 6529.47450739945,
 6597.433267916393,
 6639.022865310823,
 6673.382121671681,
 6856.809057407605,
 6773.760231409665,
 6741.630916127977,
 6329.838385325631,
 6394.597007057185,
 6228.7000351102515,
 6237.939617996416,
 6276.009258035969,
 6359.527802299326,
 6741.630916127977,
 7320.910722817447,
 7370.649590326029,
 7466.727971326733,
 7353.999982080227,
 7419.1589873644225,
 7418.359196804388,
 7710.973656981682,
 8424.120727951933,
 8181.245623555846,
 7951.439624245161,
 8164.8655417991395,
 8192.0056873968,
 8218.314792986417,
 8180.335483382522,
 7780.302510484863,
 7624.775472551371,
 7567.016238901684,
 7434.258818297923,
 7032.725871895731,
 7068.355125354666,
 6951.677010570504,
 6753.000832477776,
 6305.688421284536,
 6568.113961592583,
 6184.60071642243,
 6295.618774935577,
 6322.578259661924,
 6297.458586187231,
 6199.600451467769,
 6308.408588079379,
 6334.618086053459,
 6580.51364490887,
 6423.646298619276,
 6505.954903317453,
 6308.418353531881,
 6488.645150482415,
 6376.597325002777,
 6534.7644530205835,
 6719.84126195697,
 6763.070478826734,
 6707.141290976198,
 6884.518528886218,
 7096.154438996308,
 7047.0356777216975,
 6978.106719498534,
 7037.4557688157865,
 7193.122940992704,
 7272.591752102869,
 7259.931819477361,
 7361.530122505655,
 6792.710091992659,
 6529.0545929417995,
 6466.955592199568,
 6225.870006974743,
 6300.74856713565,
 6329.588389741541,
 6321.088539882515,
 6351.687608756908,
 6517.194939148952,
 6512.594922747189,
 6543.084618553544,
 6517.0650586306565,
 6281.089246428276,
 6371.187264315851,
 6398.4270175290485,
 6519.554760746419,
 6734.831231549806,
 6721.861245807314,
 6710.511348635148,
 6595.293657272881,
 6446.356346688735,
 6494.885274632136,
 6676.632064264837,
 6644.0125232674745,
 6601.843346266963,
 6625.443027059489,
 6589.503720483571,
 6555.984293038013,
 6502.474984317839,
 6576.573773096342,
 6622.363003339893,
 6588.193685030229,
 6602.833563150815,
 6652.112477846484,
 6642.52280348807,
 6585.413460702489,
 6256.129726374641,
 6274.469246176171,
 6285.8792008812325,
 6290.819055030116,
 6596.423520127534,
 6595.993351944756,
 6544.314577296359,
 6476.595558638376,
 6465.295953546603,
 6489.075318665195,
 6482.2355957317595,
 6487.045569362347,
 6475.625849204782,
 6495.725103547436,
 6476.175644180727,
 6474.635632320929,
 6480.265415689183,
 6486.275563432448,
 6332.518025492586,
 6334.158133240546,
 6317.4982712696155,
 6377.667130324535,
 6388.32709827733,
 6361.14740259703,
 6376.017257124074,
 6419.546761658321,
 6460.895640648541,
 6530.024790648026,
 6453.606218627321,
 6385.507323866954,
 6409.10700465948,
 6411.156773139959,
 6371.157479685719,
 6359.377902603401,
 5738.248737482908,
 5647.930020368755,
 5575.451320160579,
 5554.231968415775,
 5623.440706853163,
 4871.404186105692,
 4451.791480938562,
 4602.088630783817,
 4365.862822997347,
 4347.033077480144,
 3880.6914614023162,
 4009.8991400210634,
 3779.063129607575,
 3820.652482865693,
 4257.344720325091,
 4278.7710996629685,
 4017.1975950858496,
 4214.597428536373,
 4139.804804357497,
 3894.062074833764,
 3956.82390566467,
 3753.9285638178153,
 3521.039611151783,
 3419.8768473051446,
 3476.0533452403306,
 3614.170534450625,
 3502.5941361905916,
 3424.5276440599255,
 3486.8886030655635,
 3313.6187144785054,
 3242.4275891829116,
 3236.704545743249,
 3252.781654336035,
 3545.8021132011613,
 3695.9937961593787,
 3745.884516454389,
 4134.368376948812,
 3896.4748740110604,
 4014.1117120947506,
 3998.9095880462764,
 4078.527078170807,
 3815.423327186393,
 3857.2294734900884,
 3654.768938415951,
 3923.8493904688044,
 3820.3412090671436,
 3865.884349907607,
 3742.634329724918,
 3843.4521289618715,
 3943.3397688478685,
 3836.6734401065833,
 3857.6493879477375,
 3845.1266599299042,
 4076.560560172918,
 4025.177190462751,
 4030.7767009282443,
 4035.22510867989,
 3678.859577333089,
 3687.3003462044685,
 3661.23635347269,
 3552.890366900807,
 3705.9867837061834,
 3630.61116201285,
 3654.9422751978864,
 3678.4989879993973,
 3657.7747446965195,
 3728.5024992708236,
 3600.950064851416,
 3575.9693049385855,
 3604.5134784699344,
 3585.059720537759,
 3600.8018741096757,
 3599.7022841577846,
 3602.3968166398067,

In [235]:
final['final'] = new
final['final'] = final['final'].shift(1)
final['final'][0] = initial_position
final.fillna(0)
# cl_price3 = cl_price2

# cl_price3["BTC-USD_percent_change_shift"] = cl_price3["BTC-USD_percent_change"].shift(-1)       # shift the percent change columnn up 1
# cl_price3["BTC-USD_percent_change_shift"] = cl_price3["BTC-USD_percent_change_shift"].fillna(0) # then change the NA at end to be 0
# cl_price3.rename({'BTC-USD_percent_change_shift': 'BTC_USD_percent_change_shift'}, axis=1, inplace=True)
# cl_price3
final

,BTC_USD,ETH_USD,BTC_USD_percent_change,ETH_USD_percent_change,BTC_USD_percent_change_shift,ETH_USD_percent_change_shift,final
Date,,,,,,,
2016-05-11,452.727997,9.996280,NaN,NaN,0.004502,0.006154,452.720000
2016-05-12,454.765991,10.057800,0.004502,0.006154,0.001988,0.044622,454.757958
2016-05-13,455.670013,10.506600,0.001988,0.044622,0.000002,-0.025403,455.661965
2016-05-14,455.670990,10.239700,0.000002,-0.025403,0.004163,-0.027086,455.662941
2016-05-15,457.567993,9.962350,0.004163,-0.027086,-0.007442,0.121352,457.559911
...,...,...,...,...,...,...,...
2021-05-06,56396.515625,3490.880371,-0.017893,-0.009056,0.017020,-0.001762,56395.519457
2021-05-07,57356.402344,3484.729004,0.017020,-0.001762,0.025235,0.119929,57355.389221
2021-05-08,58803.777344,3902.647705,0.025235,0.119929,-0.009718,0.006713,58802.738655
2021-05-09,58232.316406,3928.844727,-0.009718,0.006713,-0.040742,0.005968,58231.287811
2021-05-10,55859.796875,3952.293945,-0.040742,0.005968,NaN,NaN,55858.810187