In [1]:
import yfinance as yf

import os
os.chdir('C:\\Users\\btindol\\OneDrive - Stryker\\Linked In Learn\\Algorithmic Investing\Algorithmic Trading & Quantitative Analysis using Python')  
print(os.getcwd())  # Prints the current working directory

#####################################################################################################################################################
#imports 
#!pip install yfinance 
#!pip install pandas 
#!pip install numpy
#!pip install requests
!pip install datetime
#!pip install yahoofinancials
!pip install stocktrends
from yahoofinancials import YahooFinancials

import pandas as pd
import numpy as np
import requests
import datetime as dt
import os
import json 
from functools import reduce
import statsmodels.api as sm
from stocktrends import Renko
import pandas as pd
import numpy as np
import requests
import datetime as dt


import matplotlib.pyplot as plt
%matplotlib inline

C:\Users\btindol\OneDrive - Stryker\Linked In Learn\Algorithmic Investing\Algorithmic Trading & Quantitative Analysis using Python

WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the 'c:\users\btindol\anaconda3\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: datetime in c:\users\btindol\anaconda3\lib\site-packages (4.3)
Requirement already satisfied: zope.interface in c:\users\btindol\anaconda3\lib\site-packages (from datetime) (5.1.2)
Requirement already satisfied: pytz in c:\users\btindol\anaconda3\lib\site-packages (from datetime) (2020.1)
Requirement already satisfied: setuptools in c:\users\btindol\anaconda3\lib\site-packages (from zope.interface->datetime) (50.3.1.post20201107)

WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
You should consider upgrading via the 'c:\users\btindol\anaconda3\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: stocktrends in c:\users\btindol\anaconda3\lib\site-packages (0.1.4)

In [8]:
# More than 1 ticker
stocks = ['BTC-USD','ETH-USD']
end_date = (dt.date.today()).strftime('%Y-%m-%d')
beg_date = (dt.date.today()-dt.timedelta(1825)).strftime('%Y-%m-%d') # 1825 is 5 years ish 


# Used to make a dataframe of percent change from the daily price data!!!
def get_daily_returns(df):
    daily_return = df.pct_change()
    cols = daily_return.columns.tolist()
    newcols = []
    for j in range(0,len(cols)):
        colz = cols[j] + "_" + "percent_change"

        newcols.append(colz)
    daily_return.columns = newcols               
    return daily_return


def get_stock_data(stocks, begin_date,end_date):
    cl_price = pd.DataFrame()

    # looping over tickers and creating a dataframe with closing prices
    for ticker in stocks:
        cl_price[ticker] = yf.download(ticker,beg_date,end_date)['Adj Close']

    cl_price_plus_ret = get_daily_returns(cl_price)
    final = cl_price.merge(cl_price_plus_ret, on='Date', how='left')
    return final



cl_price2 = get_stock_data(stocks,beg_date,end_date)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [9]:
cl_price3 = cl_price2
cl_price3

,BTC-USD,ETH-USD,BTC-USD_percent_change,ETH-USD_percent_change
Date,,,,
2016-05-13,455.670013,10.506600,NaN,NaN
2016-05-14,455.670990,10.239700,0.000002,-0.025403
2016-05-15,457.567993,9.962350,0.004163,-0.027086
2016-05-16,454.162994,11.171300,-0.007442,0.121352
2016-05-17,453.782990,12.198800,-0.000837,0.091977
...,...,...,...,...
2021-05-08,58803.777344,3902.647705,0.025235,0.119929
2021-05-09,58232.316406,3928.844727,-0.009718,0.006713
2021-05-10,55859.796875,3952.293945,-0.040742,0.005968
2021-05-11,56704.574219,4168.701172,0.015123,0.054755
2021-05-12,56401.492188,4264.525879,-0.005345,0.022987

In [22]:
stocks = ['ETH-USD']
end_date = (dt.date.today()).strftime('%Y-%m-%d')
beg_date = (dt.date.today()-dt.timedelta(1825)).strftime('%Y-%m-%d') # 1825 is 5 years ish 



def single_stock_analyzer(stocks, begin_date,end_date):
    cl_price = pd.DataFrame()

    # looping over tickers and creating a dataframe with closing prices
    for ticker in stocks:
        cl_price[ticker] = yf.download(ticker,beg_date,end_date)['Adj Close']     # get just adjusted close column

    cl_price_plus_ret = get_daily_returns(cl_price)
    final = cl_price.merge(cl_price_plus_ret, on='Date', how='left')
    
    #########################################################################################
    #########################################################################################
    # for each of the column names for the % change columns 
    pctchg = [col for col in cl_price_plus_ret.columns if 'percent_change' in col] # grabe % change columns
    colnew = []                                                                    # initiate empty list
    for i in range(0,len(pctchg)):                                                 # loop over column names
        print(pctchg[i])
        var1 = cl_price3[pctchg[i]].shift(-1)                                      # grab colunmn by name and shift up one
        colnew.append(var1)                                                        # append to list
    colnew = pd.DataFrame(colnew)                                                  # now its wide dataframe
    colnew = colnew.transpose()                                                    # make it narrow
    #########################################################################################
    #########################################################################################
    cols = colnew.columns.tolist()                                                 # take column names of narrow dataframe                                                
    newcols = []                                                                   # make list to add the text shift to the column name
    for j in range(0,len(cols)): 
        colz = cols[j] + "_" + "shift"                                             # add shift to the name of shifted column
           
        newcols.append(colz) 
    colnew.columns = newcols                                                       # assign the new shifted columns to origional
    
    final_f= final.merge(colnew, on='Date', how='left')

    final_f =final_f.fillna(0)     
    # fill na
    final_f.columns = final_f.columns.str.replace("-", "_")                         # replace all innapropriate characthers with  underscores in column names
    return final_f

In [23]:
cl_price2z = single_stock_analyzer(stocks,beg_date,end_date)
cl_price2z

[*********************100%***********************]  1 of 1 completed
ETH-USD_percent_change

                ETH_USD  ETH_USD_percent_change  ETH_USD_percent_change_shift
Date
2016-05-13    10.506600                0.000000                     -0.025403
2016-05-14    10.239700               -0.025403                     -0.027086
2016-05-15     9.962350               -0.027086                      0.121352
2016-05-16    11.171300                0.121352                      0.091977
2016-05-17    12.198800                0.091977                      0.111470
...                 ...                     ...                           ...
2021-05-08  3902.647705                0.119929                      0.006713
2021-05-09  3928.844727                0.006713                      0.005968
2021-05-10  3952.293945                0.005968                      0.054755
2021-05-11  4168.701172                0.054755                      0.022987
2021-05-12  4261.724121                0.022315                      0.000000

[1822 rows x 3 columns]

In [24]:
shiftval = [col for col in cl_price2z.columns if 'shift' in col]
shiftval

['ETH_USD_percent_change_shift']

In [27]:
initial_position = 10.506600
new = [(cl_price2z[shiftval[0]][0] * initial_position) + initial_position] # get first value in final for iterate the 0 of this 
for i in range(1, len(cl_price2z.index)): # starting at second row of the dataframe column 
    new.append((new[i-1]*cl_price2z[shiftval].values[i][0]) +new[i-1])
new

[10.239699947090712,
 9.962349531400152,
 11.17129953040623,
 12.198799645837253,
 13.558599935408733,
 14.769699516246256,
 13.63559959693088,
 14.014999836506759,
 14.28609987095362,
 13.461499681046577,
 12.732299344257031,
 12.525999569918008,
 12.43039944520131,
 11.295799800562207,
 11.892900036843168,
 12.350399524388244,
 12.725299375027745,
 14.077299562647408,
 14.001499623371913,
 13.737999419277665,
 13.846699213930805,
 13.740399817445256,
 13.974999876100227,
 13.934099647171562,
 14.511999559134646,
 14.417699292464203,
 14.398599103945926,
 13.908599350547329,
 14.191599332683975,
 15.743699458135902,
 17.60269864322937,
 18.893199237430917,
 18.354298881552634,
 20.588599414158292,
 15.37679902737314,
 11.330699510909039,
 12.234199081507812,
 11.83949999910139,
 13.30669927160547,
 13.095099929281824,
 13.676199418460746,
 14.33209939626771,
 14.282999475863106,
 13.850199198545452,
 13.883899186645628,
 12.175599611581017,
 12.611199876590385,
 12.46149971720898,
 12.199499642760191,
 12.128399410345995,
 11.720199161130443,
 11.470999302893572,
 10.611399266840099,
 10.528899765734122,
 10.109399429952111,
 11.394599502494751,
 10.965499481390943,
 10.947599968793602,
 10.458999255566578,
 10.516099549522202,
 10.50049934561857,
 11.51319938986849,
 11.951599642569573,
 11.652799184930089,
 11.15869958579352,
 11.034399587236749,
 11.619099196829914,
 12.450599220166643,
 12.65069915799891,
 14.661899036440976,
 14.299699266213793,
 12.749499813605729,
 13.836099124287278,
 11.989499612207322,
 12.97279978569424,
 12.843599808676968,
 12.794599070397682,
 12.460999991885252,
 11.87589983909368,
 10.941599450211765,
 8.787279764933535,
 10.293899163880742,
 11.04279955031189,
 10.925399385184804,
 10.881099307441097,
 10.911599718325434,
 11.245400022111347,
 12.244299445827616,
 12.14319948152709,
 11.690899426167036,
 11.778499177332716,
 11.571299134471563,
 11.194799972061285,
 11.218399595841655,
 11.139699533074845,
 10.752799598945957,
 10.756099311961398,
 10.748699753207987,
 11.247399877080534,
 11.179199768157654,
 11.120899751955376,
 11.030599195223303,
 11.035999852681812,
 11.357399529779933,
 11.295399257363808,
 11.148199631949595,
 10.929299912997857,
 10.98379953718669,
 11.228899549685591,
 11.672400052446378,
 11.99489931599155,
 12.112999478041564,
 11.758699945565798,
 11.679899746999386,
 11.716999583914603,
 11.68909984279706,
 11.547899782290399,
 11.345899171614269,
 11.65279918493009,
 12.168499506552127,
 11.638399656947396,
 11.89369921589142,
 11.91869978719193,
 11.923199222454024,
 11.936999842987676,
 12.555799983879423,
 12.698599356156862,
 12.431199577923847,
 13.188999652753866,
 14.430299237076925,
 13.768499830162009,
 13.247599122680667,
 13.33129929970758,
 12.877899657900473,
 13.10089922259018,
 12.823099626312837,
 13.098299506497668,
 13.274799820549564,
 13.07339907099676,
 13.224799631622828,
 13.172699451927306,
 13.199699878197,
 13.452399721048513,
 13.276999947117952,
 13.035699372958216,
 12.85429908044582,
 12.667099494625074,
 12.219099556602194,
 12.053700011191836,
 11.75549941467568,
 11.785699418161213,
 11.933499858373036,
 11.96299986493564,
 11.938199565234333,
 11.983399911500172,
 11.951599642569578,
 12.004999680311355,
 12.588499567657866,
 12.022599739184173,
 12.098999539582994,
 12.175399339981816,
 12.071499387989576,
 12.035999816519418,
 11.96899942984319,
 11.413999144737549,
 11.531999170987964,
 11.499699176733646,
 11.085099773086418,
 10.444599727583885,
 11.182799888571902,
 10.998200018843667,
 10.766099540481607,
 10.75259932734676,
 10.800999250828434,
 11.090699748469845,
 11.002499182506558,
 10.873499477088489,
 10.808799352780252,
 10.833699788281159,
 10.655500026658883,
 10.524499512597348,
 10.289899453942377,
 9.877959847867421,
 10.101499192200695,
 9.966479894715151,
 10.217499363481924,
 10.059099787300852,
 9.991180058616855,
 9.476159706757828,
 9.662759431455248,
 9.57927955318746,
 9.620819697559293,
 9.905719398865523,
 9.843619944324079,
 9.231670045799357,
 9.402049678309895,
 9.328109403884143,
 8.998469980990242,
 8.72481982151353,
 8.17411965374506,
 8.587539362305556,
 8.452500037660093,
 7.759959893941797,
 7.921339702253866,
 7.443679540389019,
 6.821659795121514,
 7.86892957841672,
 8.381479913885578,
 8.230509460360656,
 8.44600933049735,
 8.125159923459897,
 8.193619431787459,
 8.52220981297125,
 8.422849350560945,
 8.265229879942483,
 7.8284699470063,
 7.858209802650807,
 7.876589490249092,
 7.865319921259654,
 7.643819532541124,
 7.660039624728004,
 7.914399814504338,
 7.5849997638551985,
 7.166149833933456,
 7.265769695748444,
 7.175079563072206,
 7.274089550183906,
 7.170819976892013,
 7.520109858364857,
 8.284159360764292,
 8.159979525167042,
 7.969099710292371,
 8.172569933036938,
 8.378510172171676,
 9.725249892452274,
 11.251599858618105,
 10.254399882472216,
 10.254699336196738,
 9.867190004201705,
 10.289799318142773,
 10.325599297011735,
 10.549599266023174,
 9.717759734642083,
 9.861329675739313,
 9.76949942545904,
 9.646659502227887,
 9.904259323539902,
 9.636500010102603,
 10.30230008063017,
 10.227799999400931,
 10.397199254749657,
 10.600599859271645,
 10.909199320157848,
 10.70319995321763,
 10.82079943626964,
 10.632499310327558,
 10.570499991585717,
 10.589099501105986,
 10.537299728809268,
 10.564999198327607,
 10.48399982686709,
 10.571199988508646,
 10.727499573920932,
 10.732099144982628,
 10.821399297392968,
 11.114499643849422,
 11.433499876454235,
 11.352999276643162,
 11.38939911663545,
 11.515299380637282,
 11.431199614086246,
 11.032199460668368,
 11.27889973861233,
 11.349499292028518,
 11.399200027230732,
 11.269499371215451,
 13.025199419114289,
 12.919699201676988,
 12.90369940824923,
 12.67649986202195,
 12.810199274301318,
 12.758499637804203,
 12.430099991476796,
 12.668399352671331,
 12.599699518424725,
 13.119399549985129,
 13.06919908945919,
 13.548699842688139,
 14.51999993268567,
 15.396499077014749,
 15.817199135043413,
 17.349700300327623,
 19.030198362725727,
 19.458998930105015,
 18.618899625768222,
 19.302298801494324,
 19.605698830195504,
 18.888598712694947,
 16.651299828146936,
 17.754699064978773,
 19.332299487054936,
 21.47249907091507,
 23.43769942404305,
 28.592898288522022,
 28.654599107213624,
 35.05589930602511,
 46.34579681645652,
 46.827997421577585,
 34.1601969763553,
 44.740099242686455,
 43.39019999950986,
 43.1450980796624,
 42.342096704892256,
 43.678396552808685,
 53.10749624845093,
 51.2499981466772,
 50.521596988935904,
 49.666898838691495,
 50.774896692910744,
 53.12609671164548,
 52.20579721489642,
 50.03729830039462,
 50.699499204182224,
 48.74869742536266,
 44.35639793209913,
 44.64189749452869,
 45.303999216190974,
 43.24209819822496,
 42.16259994624658,
 44.30709678642104,
 43.26699672637731,
 43.43519816682794,
 43.407198289910795,
 46.28729843600362,
 50.219396682481396,
 47.57409877399132,
 49.10149968921582,
 48.71849646820285,
 48.304598015152834,
 50.707498624058964,
 48.30529991942432,
 49.67219745300184,
 48.224397822740556,
 48.55299964801573,
 48.48929802068066,
 50.03149996076055,
 49.891199215101736,
 52.720296860597514,
 62.16769947305835,
 70.15920003855871,
 68.37689724656575,
 79.02119922980633,
 76.29699431123026,
 77.26379878066284,
 79.7181978007926,
 96.98139602905303,
 94.39849512148035,
 97.81349591351307,
 94.00729793103712,
 91.42039922087464,
 91.16289953536223,
 89.524899106315,
 89.87969645676594,
 88.65539993121521,
 90.83540015755696,
 90.78649574038015,
 92.41489839145414,
 89.43800030574654,
 89.8603940892999,
 96.90629990139757,
 129.5269881138451,
 126.52099914784185,
 157.93699074858068,
 174.26099528521866,
 181.95198926978918,
 190.04599837650446,
 174.44599283712245,
 160.40299407737282,
 157.7579899005616,
 170.51099542082767,
 194.9089895336549,
 231.91098709694117,
 230.66899800611228,
 222.23899037639123,
 223.7749858042444,
 224.37599896610408,
 245.33199186062888,
 248.4639955315478,
 264.46599385424435,
 258.0710050718306,
 261.6659756449528,
 281.7369893234337,
 337.6679870566941,
 340.6089964718245,
 401.48997571553485,
 397.5369729287974,
 359.0529960489859,
 361.9330008276505,
 370.22697635779866,
 379.4139877443243,
 371.45799437968833,
 370.05598637374766,
 359.0049919003312,
 336.87199709524464,
 336.37099003328416,
 341.73900131377343,
 323.6960026986734,
 303.24797487367,
 272.6919762227888,
 293.08800209654777,
 327.92699009449893,
 302.8829846524939,
 294.9159744425532,
 274.6010032533631,
 287.9869890974188,
 282.89800002363637,
 273.3029991499115,
 268.7739770968949,
 270.5490014467683,
 245.99098841882926,
 251.69699712361913,
 242.1369846519493,
 215.35698684108132,
 197.40399981940595,
 230.77399372985445,
 209.7329941245365,
 199.66199534322016,
 170.65499260800323,
 157.3630009011735,
 193.42398897700454,
 234.39099799358615,
 199.7029957079484,
 227.26499117120147,
 218.30498478134962,
 229.4759896264027,
 225.95099585739055,
 224.71099040906807,
 206.70999923873802,
 203.9529955542582,
 204.31798577543427,
 193.1229941148423,
 205.78899402302034,
 197.97798966681313,
 203.8709948248017,
 226.76898899187253,
 219.9519878956182,
 225.34198709035135,
 223.0729899800209,
 256.5069792494833,
 261.56697662509544,
 269.17998294158775,
 296.7690017192933,
 296.02699735159473,
 295.891987590852,
 308.8640025026122,
 310.6010019515169,
 298.06398458261987,
 300.09697401105524,
 289.8179826835495,
 302.26698736031676,
 301.4569898310145,
 295.58998564864817,
 297.4699904634752,
 301.42799813284415,
 321.5909917884676,
 314.7849922787295,
 317.51900096892365,
 325.610980656767,
 331.91499654207996,
 333.881976451418,
 347.89299279044917,
 347.74699670197873,
 370.6669787832935,
 378.4849716646386,
 383.04197833578377,
 387.7409832928096,
 348.9839961689645,
 347.48399622320807,
 295.17097931614404,
 312.9879952734005,
 334.33800060484873,
 329.4279971202968,
 296.49699855530133,
 294.40498813290657,
 288.7469988355599,
 294.5320022884697,
 291.4639787177762,
 277.1119894906848,
 213.90799702531615,
 250.46399545922299,
 246.52199425900176,
 251.748983816075,
 293.4969986637886,
 282.80397536883333,
 283.7419941337405,
 258.57997722139373,
 264.30998800051094,
 286.16798891905756,
 282.4829914937222,
 292.33199016099627,
 287.4379778868036,
 306.4669994154654,
 299.15498796113525,
 291.4669999579013,
 301.4649854361939,
 302.3369946820037,
 297.4749953461065,
 292.46300211914905,
 292.6579789187388,
 295.86299589268145,
 308.58800153603033,
 311.1239816689326,
 308.60799054897933,
 297.39198753660816,
 299.86998427316973,
 303.4559826786477,
 304.13597532983874,
 338.75697627512596,
 339.627978440894,
 336.5949890486211,
 333.38399062958223,
 317.0819892659767,
 314.3189888776122,
 308.0880015541115,
 304.0060009693046,
 300.18700086326817,
 295.4460037202609,
 286.95000183023103,
 298.3279921414318,
 297.92497701928704,
 296.52699733351324,
 297.42299339486186,
 296.2979934355446,
 305.0880016625987,
 307.75099595106406,
 305.87898674141667,
 291.69398969578646,
 287.4289752015821,
 305.7109874799138,
 300.468983274946,
 296.2629897747011,
 298.8919874823646,
 294.65898592645567,
 309.0699961475065,
 320.88399108161224,
 299.2529799009509,
 314.68098837624024,
 307.9079783672623,
 316.71599196475904,
 337.6309997533441,
 333.35698257391846,
 330.92399926346343,
 332.3940004310078,
 347.6119869412357,
 354.38597351267833,
 366.72999772449197,
 360.4009879435985,
 380.6519942913517,
 410.1659702748368,
 474.9109935682671,
 466.2759841149047,
 471.3299695278436,
 480.3549936155396,
 472.9019909553706,
 427.52299479364956,
 447.11399750316065,
 466.53999167371694,
 463.4489883675263,
 465.85297997981087,
 470.2039930060615,
 463.28098910602336,
 428.5879971965427,
 434.407973792719,
 456.0309893682008,
 473.5019970371885,
 441.72099232709087,
 515.135967699573,
 651.43100671613,
 702.7670033948535,
 695.8159538415326,
 684.4479732955948,
 696.2089591984144,
 719.9749495499167,
 794.6449907949814,
 826.8229681469735,
 819.0859689150432,
 821.0629585896442,
 674.8599609470077,
 719.386997911022,
 694.1479851518503,
 765.8339566806075,
 773.8359705513917,
 762.8419523942742,
 737.0229836013875,
 753.5919527287764,
 717.2569931052357,
 756.732943826128,
 772.640963270387,
 884.4439377429484,
 962.719935888863,
 980.9219615978217,
 997.7199346231793,
 1041.68001604129,
 1153.1700022439197,
 1148.5299877632763,
 1299.7399432326615,
 1255.8199008756033,
 1154.9300119458987,
 1273.199905129913,
 1396.4199934474166,
 1366.76997010557,
 1291.919997226387,
 1053.689903302296,
 1014.2499633222889,
 1036.2799918225053,
 1039.0999380095916,
 1155.1499826410688,
 1049.5799180993606,
 1003.2599734853384,
 986.2289682418453,
 1058.7799910088515,
 1056.0299911082982,
 1055.1700057878347,
 1107.0699062547599,
 1246.0099647069167,
 1182.3599425945915,
 1071.1299661481842,
 1118.310018152978,
 1036.7900015696873,
 915.7849400275518,
 964.0189470723569,
 834.6819766518357,
 697.9509635299507,
 793.121980596151,
 757.0679657866694,
 817.8069772620762,
 883.8649582716987,
 860.4149469126761,
 814.6599436844742,
 868.7069388003179,
 845.257965038914,
 923.5609407229157,
 936.9759793002956,
 944.209987827759,
 974.1149550080424,
 923.9209870966142,
 943.864956101955,
 895.3709393009275,
 849.9709775637926,
 812.8449413087029,
 864.1889946277602,
 840.5149842534004,
 844.8099670082398,
 869.3149710048926,
 878.2649828882701,
 855.1989436833309,
 872.1999806661888,
 856.8529963578914,
 857.2249445866282,
 866.6779471744725,
 853.6839901248338,
 816.9509592266257,
 752.8309664281709,
 704.595982820901,
 728.91598926565,
 686.8899898088484,
 723.3389631001412,
 699.8309683447778,
 690.8270013852266,
 614.2909934107646,
 611.3039940070629,
 601.6659938673149,
 552.7789717094056,
 538.6439624549364,
 556.7259930510468,
 557.1749676441858,
 561.7319743153311,
 539.7020068502687,
 539.6189990407705,
 526.4390068416094,
 524.2869683452135,
 489.95097105172925,
 450.1159810371799,
 446.2789755607008,
 385.9679731030194,
 394.6449747423632,
 396.4569863955865,
 379.6069809014075,
 386.424973818915,
 416.89299029524346,
 380.5429855062312,
 383.23198077031884,
 370.2849902717162,
 385.31398142745064,
 400.5079811221398,
 398.5259865649072,
 414.2429964945893,
 430.53999297556334,
 492.94099169555614,
 492.73496753308456,
 501.4779786915257,
 531.702007139568,
 511.14698468952747,
 502.8939942653191,
 524.7889824872157,
 567.8889565145547,
 615.7179953122858,
 605.3949976387152,
 621.859962863615,
 642.5479503967377,
 708.1579944108399,
 615.4159933700819,
 662.808997027331,
 647.0319590236477,
 683.6779537921907,
 688.8809565337251,
 669.9239870044108,
 673.612951714759,
 687.1489619674519,
 779.5430015950119,
 785.6239950274523,
 816.1199656043324,
 792.3109454692299,
 753.7249483294358,
 752.8569674037929,
 752.2749972099946,
 727.2769512389839,
 679.5859739596978,
 686.0479488236734,
 733.4959451547152,
 730.5489848120656,
 708.8709460452142,
 707.0499622243466,
 672.6569580969864,
 694.3669792845562,
 696.5300041086798,
 715.3689926852294,
 699.2219595777386,
 647.7410044081635,
 583.5850008688234,
 601.7549831219095,
 586.7339875713548,
 587.2800080594218,
 572.668009076108,
 516.0359920810887,
 565.3879800424962,
 559.5900066193524,
 577.6449986422218,
 580.0430088094103,
 591.8079619972426,
 618.3289571319298,
 592.9849639078043,
 609.302956481769,
 607.1240014824402,
 605.1869898337372,
 601.0770046308016,
 597.5619901094755,
 526.4789848675074,
 533.2839772972038,
 496.84296909351366,
 477.4939707697824,
 519.7419855994148,
 491.0039800468531,
 499.64198022276355,
 500.44797994947606,
 518.8909724465957,
 537.9569507610305,
 536.2679859783575,
 527.3669853236765,
 465.8169692389258,
 474.5199718538919,
 457.67198051979625,
 460.30998091268106,
 432.7719875237553,
 442.3649742373968,
 422.3649749606447,
 436.0089869184164,
 455.17997621538177,
 453.9179828528154,
 475.3469676735951,
 464.1949905378148,
 467.3179762647239,
 474.41197014881305,
 474.0119762667934,
 491.65998588250534,
 489.11897034939454,
 476.6819895979737,
 434.42399552065535,
 446.51798922393255,
 430.0739895744464,
 434.0269923611838,
 436.0859827652414,
 449.8499898358612,
 480.6579721202082,
 501.0019960427227,
 480.51298311177953,
 469.61897105456126,
 450.69798174855526,
 462.4359879158777,
 459.656996317154,
 450.8529805222471,
 479.37296850456784,
 472.49299438812983,
 464.03697052399804,
 469.6659681231743,
 466.8979933697553,
 466.6649916691968,
 457.08097712319966,
 433.86698870486066,
 420.74699406212363,
 412.62098727590137,
 418.2619782828471,
 407.25199943294746,
 410.51597636569545,
 406.6579747962257,
 380.21498258840523,
 356.612993695816,
 365.5879994747739,
 334.17598278844207,
 322.1119878633769,
 319.5699957678014,
 286.49498475684186,
 278.93199674908766,
 282.3640034609156,
 288.04597957380116,
 315.7289924887327,
 295.8120010214788,
 300.83400401369926,
 274.31499252151843,
 281.94399004837,
 271.3409936056279,
 277.10399388550525,
 282.96700026528174,
 279.6459859810807,
 275.1969810150143,
 285.60298649808317,
 296.49898219780783,
 289.3120012565344,
 284.1050007124102,
 283.0039875686317,
 295.3409927377304,
 294.37099155210484,
 289.2589922252483,
 285.7229816109314,
 232.33098525069835,
 230.21498801276474,
 217.2029950751065,
 197.95099686993768,
 196.92398885043613,
 197.07898762412785,
 185.0659875702655,
 183.3309870226557,
 211.35399626318275,
 211.74898526257087,
 223.07399706006257,
 220.5889965395746,
 197.87499284436586,
 209.97499851031628,
 209.96898654764308,
 224.59099529621994,
 246.58399071672082,
 240.47998703120624,
 244.3299929954964,
 228.72998745611437,
 218.50499698114797,
 215.8469923165256,
 228.4939950330078,
 222.40198475526262,
 231.63498613035952,
 232.84799878180658,
 230.76799702596975,
 227.1809915404501,
 220.48899043967546,
 222.21799428340054,
 227.6009896942073,
 225.11998697630912,
 226.11899511889354,
 229.25499659240228,
 227.98198638453113,
 225.76898902803498,
 189.4989860671843,
 196.726997890763,
 199.84099619123927,
 195.71498926036745,
 209.7039871675777,
 210.11998751874506,
 207.0829850650938,
 203.3519976511871,
 203.7269976376262,
 205.4299852469405,
 205.14199087258945,
 204.0439989689361,
 204.33599114587696,
 203.8519976331059,
 202.71898680982045,
 203.32898739811293,
 204.20999932914407,
 205.3659898879266,
 197.24698688563075,
 197.55599261176107,
 197.38098956633178,
 198.87198682686684,
 200.63498725139377,
 200.18599739946626,
 207.48598492844997,
 209.09099585673707,
 218.45198794986177,
 217.18299080336894,
 212.2309951328356,
 210.07399753017373,
 212.53299707503948,
 211.33998869532996,
 210.41799165835909,
 206.82599654899641,
 181.39699661407784,
 180.8059932174812,
 175.17699561830486,
 174.00100078778476,
 177.0669949396064,
 149.17499765723227,
 130.33899980323088,
 136.70099908488447,
 126.70599669974568,
 123.2959931609502,
 113.49399919168333,
 116.44999273713125,
 108.33499516681948,
 110.00999815800517,
 122.43799911238746,
 117.54264406480586,
 113.17141314377848,
 118.63555479188513,
 116.38889654793437,
 108.92501437155718,
 110.21418363646117,
 102.47555171416022,
 91.76105167437615,
 93.29455991970207,
 92.15963411845856,
 95.14205588560704,
 91.68565037095051,
 88.94530165413012,
 90.59329658965186,
 86.53931114055057,
 84.30829315482328,
 84.4408081036445,
 85.26209713644472,
 95.13382376920552,
 101.11245361892189,
 101.26857391356917,
 116.2168689662647,
 109.49622711945547,
 116.75949437388816,
 130.7652540602774,
 140.23800152045453,
 129.8443403972908,
 131.86562633493844,
 116.5759082599216,
 137.64701345497116,
 138.01833607337917,
 139.8594462362924,
 133.36825079231866,
 140.8194071390779,
 155.0476781089245,
 149.13500437254564,
 154.58193410721222,
 155.63858995279008,
 157.74619485704278,
 151.69921326419268,
 150.35962896204933,
 150.80311039132448,
 128.62517845407388,
 127.54831997250784,
 125.96652529093979,
 116.89780003294914,
 129.06872091850303,
 122.03271043075453,
 123.54706126710525,
 123.74191599638698,

In [28]:
new2 = pd.DataFrame(new)
new2.tail()

                0
1817  3928.844584
1818  3952.293802
1819  4168.701021
1820  4264.525725
1821  4264.525725

# SINGLE STOCK ANALYZER NOW MAKE STRATEGY OFF OF IT

In [29]:
stocks = ['ETH-USD']
end_date = (dt.date.today()).strftime('%Y-%m-%d')
beg_date = (dt.date.today()-dt.timedelta(1825)).strftime('%Y-%m-%d') # 1825 is 5 years ish 



# Used to make a dataframe of percent change from the daily price data!!!
def get_daily_returns(df):
    daily_return = df.pct_change()
    cols = daily_return.columns.tolist()
    newcols = []
    for j in range(0,len(cols)):
        colz = cols[j] + "_" + "percent_change"

        newcols.append(colz)
    daily_return.columns = newcols               
    return daily_return




def single_stock_analyzer(stocks, begin_date,end_date,initial_position):
    cl_price = pd.DataFrame()

    # looping over tickers and creating a dataframe with closing prices
    for ticker in stocks:
        cl_price[ticker] = yf.download(ticker,beg_date,end_date)['Adj Close']     # get just adjusted close column

    cl_price_plus_ret = get_daily_returns(cl_price)
    final = cl_price.merge(cl_price_plus_ret, on='Date', how='left')
    
    #########################################################################################
    #########################################################################################
    # for each of the column names for the % change columns 
    pctchg = [col for col in cl_price_plus_ret.columns if 'percent_change' in col] # grabe % change columns
    colnew = []                                                                    # initiate empty list
    for i in range(0,len(pctchg)):                                                 # loop over column names
        print(pctchg[i])
        var1 = cl_price3[pctchg[i]].shift(-1)                                      # grab colunmn by name and shift up one
        colnew.append(var1)                                                        # append to list
    colnew = pd.DataFrame(colnew)                                                  # now its wide dataframe
    colnew = colnew.transpose()                                                    # make it narrow
    #########################################################################################
    #########################################################################################
    cols = colnew.columns.tolist()                                                 # take column names of narrow dataframe                                                
    newcols = []                                                                   # make list to add the text shift to the column name
    for j in range(0,len(cols)): 
        colz = cols[j] + "_" + "shift"                                             # add shift to the name of shifted column
           
        newcols.append(colz) 
    colnew.columns = newcols                                                       # assign the new shifted columns to origional
    
    final_f= final.merge(colnew, on='Date', how='left')

    final_f =final_f.fillna(0)     
    # fill na
    final_f.columns = final_f.columns.str.replace("-", "_")                         # replace all innapropriate characthers with  underscores in column names
    
    #########################################################################################
    #########################################################################################
    # Calculate returns from initial position entry 
    shiftval = [col for col in final_f.columns if 'shift' in col]                   # find the shift column to bring % change up to today to mutliply to get positions next day amount.. 
    
    initial_position = initial_position                                             # pass from function above
    
    new = [(final_f[shiftval[0]][0] * initial_position) + initial_position]        # get first value in final for iterate the 0 of this 
    for i in range(1, len(final_f.index)):                                          # starting at second row of the dataframe column 
        new.append((new[i-1]*final_f[shiftval].values[i][0]) +new[i-1])

    final_f['Position'] = new
    final_f['Position'] = final_f['Position'].shift(1)
    final_f['Position'][0] = initial_position
    final_f.fillna(0)
    
    return final_f

In [30]:
# THE FINAL VALUE IS NOT GOING TO BE THE SAME BECAUSE IT IS TODAY AND TODAY IS NOT DONE!!!!!!!!
var = single_stock_analyzer(stocks,beg_date,end_date,10.506600)
var

[*********************100%***********************]  1 of 1 completed
ETH-USD_percent_change

,ETH_USD,ETH_USD_percent_change,ETH_USD_percent_change_shift,Position
Date,,,,
2016-05-13,10.506600,0.000000,-0.025403,10.506600
2016-05-14,10.239700,-0.025403,-0.027086,10.239700
2016-05-15,9.962350,-0.027086,0.121352,9.962350
2016-05-16,11.171300,0.121352,0.091977,11.171300
2016-05-17,12.198800,0.091977,0.111470,12.198800
...,...,...,...,...
2021-05-08,3902.647705,0.119929,0.006713,3902.647564
2021-05-09,3928.844727,0.006713,0.005968,3928.844584
2021-05-10,3952.293945,0.005968,0.054755,3952.293802
2021-05-11,4168.701172,0.054755,0.022987,4168.701021
2021-05-12,4274.333008,0.025339,0.000000,4264.525725

In [150]:
#def get_return(df,initial_amount):

pctchg = [col for col in cl_price3.columns if 'percent_change' in col]
pctchg

['BTC-USD_percent_change', 'ETH-USD_percent_change']

In [151]:
colnew = []
for i in range(0,len(pctchg)):
    print(pctchg[i])
    var1 = cl_price3[pctchg[i]].shift(-1)
    colnew.append(var1)
    
colnew

BTC-USD_percent_change
ETH-USD_percent_change

[Date
 2016-05-11    0.004502
 2016-05-12    0.001988
 2016-05-13    0.000002
 2016-05-14    0.004163
 2016-05-15   -0.007442
                 ...
 2021-05-06    0.017020
 2021-05-07    0.025235
 2021-05-08   -0.009718
 2021-05-09   -0.040742
 2021-05-10         NaN
 Name: BTC-USD_percent_change, Length: 1822, dtype: float64,
 Date
 2016-05-11    0.006154
 2016-05-12    0.044622
 2016-05-13   -0.025403
 2016-05-14   -0.027086
 2016-05-15    0.121352
                 ...
 2021-05-06   -0.001762
 2021-05-07    0.119929
 2021-05-08    0.006713
 2021-05-09    0.005968
 2021-05-10         NaN
 Name: ETH-USD_percent_change, Length: 1822, dtype: float64]

In [153]:
colnew = pd.DataFrame(colnew)
colnew

Date,2016-05-11,2016-05-12,2016-05-13,2016-05-14,2016-05-15,2016-05-16,2016-05-17,2016-05-18,2016-05-19,2016-05-20,...,2021-05-01,2021-05-02,2021-05-03,2021-05-04,2021-05-05,2021-05-06,2021-05-07,2021-05-08,2021-05-09,2021-05-10
BTC-USD_percent_change,0.004502,0.001988,0.000002,0.004163,-0.007442,-0.000837,0.001842,-0.034983,0.009029,0.001157,...,-0.020699,0.010051,-0.06760,0.076696,-0.017893,0.017020,0.025235,-0.009718,-0.040742,NaN
ETH-USD_percent_change,0.006154,0.044622,-0.025403,-0.027086,0.121352,0.091977,0.111470,0.089323,-0.076786,0.027824,...,0.002092,0.162270,-0.05172,0.082724,-0.009056,-0.001762,0.119929,0.006713,0.005968,NaN

In [154]:
colnew = colnew.transpose()
colnew

            BTC-USD_percent_change  ETH-USD_percent_change
Date
2016-05-11                0.004502                0.006154
2016-05-12                0.001988                0.044622
2016-05-13                0.000002               -0.025403
2016-05-14                0.004163               -0.027086
2016-05-15               -0.007442                0.121352
...                            ...                     ...
2021-05-06                0.017020               -0.001762
2021-05-07                0.025235                0.119929
2021-05-08               -0.009718                0.006713
2021-05-09               -0.040742                0.005968
2021-05-10                     NaN                     NaN

[1822 rows x 2 columns]

In [155]:
cols = colnew.columns.tolist()
cols

['BTC-USD_percent_change', 'ETH-USD_percent_change']

In [156]:
cols = colnew.columns.tolist()

newcols = []
for j in range(0,len(cols)):
    colz = cols[j] + "_" + "shift"
           
    newcols.append(colz)
colnew.columns = newcols                         # replace old column to noew

In [157]:
colnew

            BTC-USD_percent_change_shift  ETH-USD_percent_change_shift
Date
2016-05-11                      0.004502                      0.006154
2016-05-12                      0.001988                      0.044622
2016-05-13                      0.000002                     -0.025403
2016-05-14                      0.004163                     -0.027086
2016-05-15                     -0.007442                      0.121352
...                                  ...                           ...
2021-05-06                      0.017020                     -0.001762
2021-05-07                      0.025235                      0.119929
2021-05-08                     -0.009718                      0.006713
2021-05-09                     -0.040742                      0.005968
2021-05-10                           NaN                           NaN

[1822 rows x 2 columns]

In [158]:
final= cl_price3.merge(colnew, on='Date', how='left')
final

,BTC-USD,ETH-USD,BTC-USD_percent_change,ETH-USD_percent_change,BTC-USD_percent_change_shift,ETH-USD_percent_change_shift
Date,,,,,,
2016-05-11,452.727997,9.996280,NaN,NaN,0.004502,0.006154
2016-05-12,454.765991,10.057800,0.004502,0.006154,0.001988,0.044622
2016-05-13,455.670013,10.506600,0.001988,0.044622,0.000002,-0.025403
2016-05-14,455.670990,10.239700,0.000002,-0.025403,0.004163,-0.027086
2016-05-15,457.567993,9.962350,0.004163,-0.027086,-0.007442,0.121352
...,...,...,...,...,...,...
2021-05-06,56396.515625,3490.880371,-0.017893,-0.009056,0.017020,-0.001762
2021-05-07,57356.402344,3484.729004,0.017020,-0.001762,0.025235,0.119929
2021-05-08,58803.777344,3902.647705,0.025235,0.119929,-0.009718,0.006713
2021-05-09,58232.316406,3928.844727,-0.009718,0.006713,-0.040742,0.005968
2021-05-10,55859.796875,3952.293945,-0.040742,0.005968,NaN,NaN

In [159]:
final.fillna(0) # replace all na vlaues with 0

,BTC-USD,ETH-USD,BTC-USD_percent_change,ETH-USD_percent_change,BTC-USD_percent_change_shift,ETH-USD_percent_change_shift
Date,,,,,,
2016-05-11,452.727997,9.996280,0.000000,0.000000,0.004502,0.006154
2016-05-12,454.765991,10.057800,0.004502,0.006154,0.001988,0.044622
2016-05-13,455.670013,10.506600,0.001988,0.044622,0.000002,-0.025403
2016-05-14,455.670990,10.239700,0.000002,-0.025403,0.004163,-0.027086
2016-05-15,457.567993,9.962350,0.004163,-0.027086,-0.007442,0.121352
...,...,...,...,...,...,...
2021-05-06,56396.515625,3490.880371,-0.017893,-0.009056,0.017020,-0.001762
2021-05-07,57356.402344,3484.729004,0.017020,-0.001762,0.025235,0.119929
2021-05-08,58803.777344,3902.647705,0.025235,0.119929,-0.009718,0.006713
2021-05-09,58232.316406,3928.844727,-0.009718,0.006713,-0.040742,0.005968
2021-05-10,55859.796875,3952.293945,-0.040742,0.005968,0.000000,0.000000

In [160]:
final.columns = final.columns.str.replace("-", "_") # replace all the underscores

In [161]:
final

,BTC_USD,ETH_USD,BTC_USD_percent_change,ETH_USD_percent_change,BTC_USD_percent_change_shift,ETH_USD_percent_change_shift
Date,,,,,,
2016-05-11,452.727997,9.996280,NaN,NaN,0.004502,0.006154
2016-05-12,454.765991,10.057800,0.004502,0.006154,0.001988,0.044622
2016-05-13,455.670013,10.506600,0.001988,0.044622,0.000002,-0.025403
2016-05-14,455.670990,10.239700,0.000002,-0.025403,0.004163,-0.027086
2016-05-15,457.567993,9.962350,0.004163,-0.027086,-0.007442,0.121352
...,...,...,...,...,...,...
2021-05-06,56396.515625,3490.880371,-0.017893,-0.009056,0.017020,-0.001762
2021-05-07,57356.402344,3484.729004,0.017020,-0.001762,0.025235,0.119929
2021-05-08,58803.777344,3902.647705,0.025235,0.119929,-0.009718,0.006713
2021-05-09,58232.316406,3928.844727,-0.009718,0.006713,-0.040742,0.005968
2021-05-10,55859.796875,3952.293945,-0.040742,0.005968,NaN,NaN

In [191]:
initial_position= 452.72
shiftval = [col for col in final.columns if 'shift' in col]
shiftval[0]

for i in range(0,len(shiftval)):
    var1 = shiftval[i]
    print(var1)
    #new = [(final.var1.values[0] * initial_position) + initial_position]
#    # print(new)
#new = [(final.BTC_USD_percent_change_shift.values[0] * initial_position) + initial_position]

# for i in range(1, len(final.index)): # starting at second row of the dataframe column 
#     new.append((new[i-1]*final.BTC_USD_percent_change_shift.values[i]) +new[i-1])

BTC_USD_percent_change_shift
ETH_USD_percent_change_shift

In [196]:
shiftval = [col for col in final.columns if 'shift' in col]
shiftval[0]

'BTC_USD_percent_change_shift'

In [201]:
var = final[shiftval[0]] # get the bitcoin shift colum n
var

Date
2016-05-11    0.004502
2016-05-12    0.001988
2016-05-13    0.000002
2016-05-14    0.004163
2016-05-15   -0.007442
                ...
2021-05-06    0.017020
2021-05-07    0.025235
2021-05-08   -0.009718
2021-05-09   -0.040742
2021-05-10         NaN
Name: BTC_USD_percent_change_shift, Length: 1822, dtype: float64

In [214]:
final[shiftval[0]][0]#.values[1]#[0]

0.004501586822668102

In [215]:
#var1 = "BTC_USD_percent_change_shift"
#BTC_USD_percent_change_shift
new = [(final[shiftval[0]][0] * initial_position) + initial_position] # get first value in final for iterate the 0 of this 
new

[454.7579583863583]

In [229]:
new = [(final[shiftval[0]][0] * initial_position) + initial_position] # get first value in final for iterate the 0 of this 
for i in range(1, len(final.index)): # starting at second row of the dataframe column 
    new.append((new[i-1]*final[shiftval].values[i][0]) +new[i-1])
new

[454.7579583863583,
 455.66196463482856,
 455.6629411800789,
 457.5599108459183,
 454.1549722113077,
 453.7749740407662,
 454.61095780914195,
 438.707247032371,
 442.6681756018592,
 443.18015996639303,
 439.31523800182964,
 444.1471533835107,
 445.97310989942633,
 449.591057466769,
 453.3759942719211,
 473.4556261584521,
 530.0306155898579,
 526.223675999534,
 533.8545836879849,
 531.3766001152278,
 536.9104989467135,
 537.9624823176505,
 569.1839156869056,
 572.7168733004289,
 574.9668335572298,
 585.526644587786,
 576.5868000594004,
 581.6347455606818,
 574.6198548229659,
 577.4597704791331,
 606.7162727365326,
 672.7721127650167,
 704.3635347159974,
 685.5469115255956,
 694.4567272875331,
 766.294447607013,
 748.8957681201161,
 756.2136320217526,
 763.7675147035823,
 737.2129910857384,
 666.6402020358495,
 596.105498250724,
 623.9659680386734,
 665.287259625571,
 665.1112373441958,
 629.355887479811,
 655.2634498692996,
 646.9895481675729,
 639.8787118590103,
 673.3250815130264,
 676.2840746556578,
 703.6895964251015,
 658.6523670583967,
 683.6499113427175,
 670.6151684433116,
 677.3190295187919,
 640.5506970594058,
 666.5112370287256,
 650.9485236465604,
 649.3485152879439,
 647.6475565640727,
 664.539286997883,
 654.4564572880436,
 658.06637887411,
 663.2432893825155,
 660.7553572550205,
 679.4469826533777,
 673.0941285613193,
 672.8521284414676,
 665.6732391357714,
 665.0002773901256,
 650.607526251955,
 655.5444507650876,
 661.2732924421739,
 654.0854311269901,
 651.7724837015417,
 654.3404315054871,
 655.023402839949,
 656.9803995216457,
 655.0354265533439,
 624.6699961300966,
 606.2612636839496,
 547.4553566281244,
 566.3449765759896,
 578.2787867737848,
 575.0328724297855,
 587.7676328351001,
 592.6795333761925,
 591.0435759455476,
 587.7906426825615,
 592.0925686466554,
 589.1095891113123,
 587.5486425627097,
 585.5776690771174,
 570.4629458285492,
 567.2299707091171,
 577.4288262015134,
 573.2058783345414,
 574.3078486154806,
 575.6198371593226,
 581.6867465952636,
 581.2977153811563,
 586.742626526704,
 583.4046727928595,
 580.1717587075055,
 577.7507809637375,
 579.6407622276291,
 569.9369541430809,
 573.9018499276486,
 574.0968538073274,
 577.4927899154113,
 575.4618199310008,
 572.2928695595446,
 575.5268212242271,
 598.2014084942834,
 608.6232214741498,
 606.5793122651721,
 610.4251915973537,
 614.5331512610973,
 626.3049159814129,
 622.8500209538392,
 623.4979587274449,
 606.7082772722961,
 608.2322371695417,
 609.230266415397,
 610.673234090942,
 607.1443047265763,
 606.9623011055427,
 605.9733049032532,
 609.8632508398567,
 609.2162285774233,
 608.3012667119257,
 597.1384389892798,
 596.28744083768,
 602.8313315943377,
 602.6143554465261,
 600.8153759931513,
 608.0322895295329,
 606.1553085242866,
 604.7173456431498,
 605.6822944186495,
 609.7242152098383,
 613.9721260147725,
 610.8812382292658,
 612.122183106145,
 610.1932010663177,
 612.5001671521077,
 613.0101679091017,
 617.11007107453,
 619.0970354885966,
 616.741120072133,
 618.9830848646967,
 641.0606978164,
 636.1807791322566,
 636.7747627807805,
 640.3666793137936,
 638.6347152782239,
 641.6196479040678,
 639.1817026865749,
 637.9487532739329,
 630.5088822500812,
 630.8458513955293,
 632.8168248811215,
 657.2823961403155,
 657.0593776187674,
 653.7494385267922,
 657.5763972947484,
 678.2920347926074,
 688.3008301656548,
 689.6388192267874,
 714.4663836034696,
 701.8516161957913,
 700.9596031436769,
 729.7801389808742,
 740.8158937528185,
 688.6878472551832,
 703.2225636591231,
 703.4056048594852,
 711.5094045854169,
 703.118561589961,
 709.8354839581648,
 723.2602346169282,
 715.5213576442356,
 716.398356313126,
 705.04156229013,
 702.0186054336007,
 705.0085428538526,
 711.6064487696702,
 744.1848527983617,
 740.9639013923244,
 751.571746242382,
 751.6027515540806,
 731.0130883935165,
 739.234928026584,
 751.3337133376098,
 744.5808418973776,
 740.2759252634544,
 741.6358865927198,
 735.3690295167701,
 732.0220427393598,
 735.7999911425641,
 735.5910104589897,
 745.6778073839085,
 756.7606194301039,
 777.9302284012183,
 771.1414078889578,
 773.8583398776594,
 758.6866108001021,
 764.2105000427716,
 768.1184510324285,
 770.7963822451943,
 772.7803559894319,
 774.6363412717958,
 769.7174218117166,
 780.0731959190281,
 780.5422428095856,
 781.4672142638993,
 778.0742688256446,
 784.8931181043533,
 790.8150105706177,
 790.516065655855,
 792.6999870401012,
 800.8618301743505,
 834.2662694166796,
 864.5247071009358,
 921.9677231917444,
 898.8061450121553,
 896.1671535412471,
 907.5939536518774,
 933.1815143696426,
 975.9037821863203,
 973.479813772723,
 961.2209971087965,
 963.7259577440944,
 998.3073781494052,
 1021.7319521717285,
 1043.8215278027485,
 1154.7095837294423,
 1013.362104899155,
 902.1850526124363,
 908.5689730502713,
 911.1828795150612,
 902.8120556972375,
 907.6629831942612,
 777.7432810198546,
 804.8197680740093,
 823.9694542288578,
 818.3975311666868,
 821.7834576859547,
 831.51930866153,
 907.921950787838,
 886.602320052639,
 899.0571171414946,
 895.0101915558977,
 921.7727193120656,
 924.6566405385768,
 920.995755497258,
 892.671243613159,
 901.5260676706863,
 917.5697906227258,
 919.7337538634181,
 921.5737482173074,
 919.4797300301714,
 920.3657617426273,
 970.385874283309,
 989.0055405035313,
 1011.7821157181708,
 1029.891842215477,
 1042.8816029992888,
 1027.3218192528745,
 1038.1316869015977,
 1061.331228277794,
 1063.0511685999688,
 994.3654311782204,
 988.6565476446881,
 1004.4322699595854,
 999.1633810954128,
 990.6245304604512,
 1004.5322437795897,
 1007.4621847010234,
 1027.421793072879,
 1046.191481057186,
 1054.4014190450148,
 1047.8514859146205,
 1079.9609040868324,
 1115.2803485650934,
 1117.4202033449178,
 1166.6993621768984,
 1173.6593222442825,
 1143.8197614383473,
 1165.1793694947323,
 1179.9491281336152,
 1179.9491281336152,
 1222.4784061951927,
 1250.9879123701544,
 1274.9674692650658,
 1255.1278538908468,
 1267.0976131606703,
 1272.807473239453,
 1223.5184268868127,
 1149.9796868093836,
 1188.4689971702728,
 1116.7002453590987,
 1175.8091866129223,
 1221.3584308611998,
 1231.898283748202,
 1239.978097081422,
 1249.5879126856244,
 1187.7890775397182,
 1100.2105463980408,
 973.8007919896962,
 1036.7216776282519,
 1054.2113589256655,
 1120.520246242146,
 1049.1214830126974,
 1038.5716205368792,
 937.5034595113685,
 972.7618088774046,
 966.7078997001089,
 1045.751547421904,
 1047.1315279288015,
 1039.9516010437767,
 1026.411923215863,
 1071.7711073447917,
 1080.4809144326423,
 1102.1505756060128,
 1143.7898547400548,
 1133.2299826754206,
 1124.760161582843,
 1182.6591632714858,
 1176.8792360709906,
 1175.9291796105588,
 1187.8490130044584,
 1187.1090358410074,
 1204.9887248977786,
 1200.3487922089082,
 1169.2593755506844,
 1167.5194160508775,
 1172.4993085550254,
 1182.9190463762347,
 1193.8889453778586,
 1211.6486414369936,
 1210.268660930096,
 1229.0582460238788,
 1222.028462971095,
 1231.6882044512213,
 1207.1886372104996,
 1250.1279422090668,
 1265.4676370696839,
 1281.05732751439,
 1317.7067045554681,
 1316.4567266350232,
 1321.7666914337885,
 1347.8662059990484,
 1421.5748649500379,
 1452.7942841947142,
 1490.0636454016067,
 1537.6428830890443,
 1555.4224762576548,
 1578.772161466092,
 1596.681757221155,
 1723.3195349454556,
 1755.3289792976634,
 1787.098437654598,
 1848.5372938075948,
 1724.2095338729914,
 1804.878152891365,
 1808.878082236789,
 1738.3993467013242,
 1734.4193144653761,
 1839.0574807898454,
 1888.616663972363,
 1987.6748507363454,
 2084.693156540508,
 2041.1638961425745,
 2173.3615121815733,
 2320.3789348035352,
 2443.596728992962,
 2304.939266122914,
 2202.381019113529,
 2038.8339812434015,
 2155.7619695434955,
 2255.5702651279016,
 2175.431543975998,
 2286.3695257786158,
 2407.83735087942,
 2488.5060919659495,
 2515.3056674075524,
 2511.7656908750423,
 2686.7625997373398,
 2863.1493766271947,
 2732.111652209296,
 2805.5705597125093,
 2823.7601798181095,
 2947.6578936380906,
 2958.0578564179805,
 2659.582904057039,
 2716.9720270568437,
 2506.3258455579803,
 2464.5365446598535,
 2518.5155716454447,
 2655.8329702957035,
 2548.245026974403,
 2589.554355881984,
 2721.7419623321666,
 2689.0525983494044,
 2705.362124711773,
 2744.8614269978348,
 2608.673891202228,
 2589.3641736944787,
 2478.4061727142284,
 2552.4048656045716,
 2574.744558887837,
 2539.2752147136475,
 2480.7962672144545,
 2434.5070458027258,
 2506.425697309828,
 2564.014767949642,
 2601.5939381372073,
 2601.9440296094567,
 2608.5139819174833,
 2518.615423397293,
 2571.2946686546716,
 2518.3954565796525,
 2372.5181505374717,
 2337.748745171469,
 2398.797715633265,
 2357.8582532392534,
 2233.300638966349,
 1998.8246782003464,
 1929.7858586365192,
 2228.370550269969,
 2318.8389229437375,
 2273.3897745836207,
 2817.55032857115,
 2667.712887402497,
 2810.0704802261125,
 2730.351673531858,
 2754.811446553628,
 2576.4344704435644,
 2529.4052718683847,
 2671.732835925552,
 2808.9603924127787,
 2726.4017921305135,
 2757.131229795828,
 2875.2892989068914,
 2718.211995388473,
 2710.6220415664584,
 2804.6804387168177,
 2895.838740609957,
 3252.8524538666757,
 3213.8831715152405,
 3378.8802570139783,
 3419.879532804574,
 3342.4109305034335,
 3381.2203035701245,
 3650.555633933318,
 3884.6413428036503,
 4073.188061150834,
 4325.053485257934,
 4181.856307655332,
 4376.552575580267,
 4331.613427977144,
 4160.546625474871,
 4193.626119285146,
 4087.5877091398347,
 4001.6693049237488,
 4100.447589405351,
 4151.446688559507,
 4334.6036095337095,
 4371.522879268352,
 4352.323023101267,
 4382.802465182493,
 4382.582742501165,
 4578.939137351692,
 4565.219164856932,
 4703.307057709715,
 4891.923354905986,
 4578.689141767602,
 4582.879009164219,
 4236.235229920941,
 4376.452479692107,
 4597.038915294259,
 4599.798632171741,
 4228.6753048653745,
 4225.985410973292,
 4122.867115262833,
 4161.196516338978,
 4130.737093435385,
 3882.5215072014594,
 3154.894223259055,
 3637.4557676725303,
 3624.9760076457123,
 3582.816596097704,
 4065.1281449270905,
 3924.9006414307955,
 3905.8809578624,
 3630.9759016638486,
 3630.635819780415,
 3792.332914741916,
 3682.7750355143517,
 3926.0007196553133,
 3892.2813445697466,
 4200.595722736879,
 4174.65623952452,
 4162.996289235369,
 4338.633323509269,
 4403.6624482751695,
 4409.24193956303,
 4317.403718039337,
 4229.285157374217,
 4328.333700753853,
 4370.732854160821,
 4426.811941707285,
 4610.39854259164,
 4771.935728268395,
 4781.90576700182,
 4826.394727244533,
 5446.813943968023,
 5647.110210631077,
 5831.687028399285,
 5678.08964388048,
 5725.488708969229,
 5605.410751895983,
 5590.591189449332,
 5708.419186265778,
 6011.344011196242,
 6031.49355761929,
 6008.313791284413,
 5930.215073160485,
 5526.542516114781,
 5750.698224606955,
 5904.7257773085375,
 5780.797790585795,
 5752.98822321902,
 6153.74139823881,
 6130.421497660508,
 6468.2856468305345,
 6767.190523237941,
 7078.374967895846,
 7207.63245032236,
 7379.819838499407,
 7407.2793143939325,
 7022.635718096502,
 7144.253687029548,
 7459.55817609867,
 7143.453896469514,
 6618.02323624734,
 6357.487799271342,
 5949.964724303516,
 6559.374369874586,
 6635.632788474234,
 7315.41081996748,
 7871.550898677337,
 7708.854065515793,
 7790.01229990906,
 8036.348280672379,
 8200.494795258062,
 8071.117197765755,
 8253.404016921897,
 8038.628025559314,
 8253.544639437949,
 8790.764642194945,
 9330.384993177295,
 9818.176181542694,
 10058.622129628542,
 9888.435682669457,
 10233.41884671452,
 10975.40574029066,
 11074.403991589903,
 11323.000186335152,
 11656.994286678051,
 11916.48970296243,
 14291.247560031576,
 17899.383044835045,
 16569.107714634978,
 15177.93209298748,
 15455.12739193441,
 16936.501615630266,
 17415.09277119214,
 16407.90939016009,
 16563.707419400554,
 17706.587622239913,
 19497.05599548531,
 19140.462684958864,
 19113.861592339395,
 17776.385217463263,
 16624.305958365632,
 15802.621253818119,
 13831.555484699684,
 14698.940553872966,
 13925.553824317145,
 14026.351848512779,
 16099.515423555062,
 15838.220234374292,
 14606.241995983717,
 14655.941313409658,
 12951.971412259056,
 14156.150337007986,
 13656.95895939003,
 14981.834970900925,
 15200.731494947351,
 15598.924656593355,
 17429.192131516666,
 17526.690409311374,
 16477.308554921303,
 15169.83165013585,
 14595.142582668264,
 14973.035321650043,
 13405.563009412035,
 13980.352661040408,
 14359.946541848289,
 13771.756736294647,
 13819.555696663412,
 11490.297035898462,
 11188.401977934489,
 11474.697702069408,
 11607.195361636577,
 12898.972348432191,
 11599.894709344979,
 10931.20730225993,
 10868.208415069505,
 11359.199742220293,
 11259.201508584694,
 11171.203062985367,
 11440.498110856985,
 11786.091615683514,
 11296.200855029867,
 10106.121290605457,
 10220.919067510074,
 9170.37805390784,
 8830.594016775629,
 9174.748093903145,
 8276.863563471004,
 6955.147164117609,
 7753.863036104321,
 7621.165184760831,
 8265.44384331344,
 8736.826141837248,
 8621.74809644578,
 8129.826609944035,
 8926.41263673974,
 8598.157692833134,
 9494.462173050213,
 10166.220814947605,
 10233.719622651633,
 11112.503904532225,
 10551.613421452052,
 11225.10152498781,
 11403.498764411817,
 10690.211559198142,
 10004.823275241648,
 10300.917654418554,
 9812.896977919321,
 9664.559754391514,
 10366.517081610657,
 10725.410156201671,
 10397.716725814014,
 10950.80656543441,
 11086.20456439511,
 11489.497245338427,
 11512.396254913829,
 11573.095378039687,
 10779.709978301997,
 9965.394284213608,
 9394.843815516997,
 9337.384869531792,
 8865.843394132176,
 9578.460689304113,
 9204.957521222648,
 9194.68719482474,
 8269.66349534019,
 8300.713728120243,
 8338.202323735839,
 7916.740041864551,
 8223.534427349518,
 8630.497941888894,
 8913.312282206325,
 8929.122549809454,
 8728.315549980467,
 8879.463270738775,
 8667.967006599483,
 8495.630206999132,
 8209.255382698935,
 7832.901679031706,
 7954.339475366062,
 7165.573622935142,
 6890.398307838556,
 6973.406607208606,
 6844.109086426827,
 7083.674678969485,
 7455.978161210897,
 6853.718779962872,
 6811.3498994586635,
 6636.202602627813,
 6910.9677687192525,
 7023.395958573901,
 6770.610384704662,
 6834.63903886158,
 6968.196738298001,
 7889.110647096464,
 7895.820489511603,
 7986.099168270493,
 8328.963229122299,
 8058.527576398275,
 7901.950264048035,
 8163.2757261315655,
 8294.16306258091,
 8845.673828531493,
 8895.422949765203,
 8802.304477418304,
 8930.72213092952,
 9697.328706812175,
 8845.583986368461,
 9281.34582034059,
 8986.891060639016,
 9348.31534051893,
 9418.913702847562,
 9240.386582905257,
 9118.84869068274,
 9235.756781873359,
 9743.68823948193,
 9700.588414857837,
 9857.976259765865,
 9654.629265740725,
 9372.844204117162,
 9234.657191921468,
 9325.014970845636,
 9043.780680743268,
 8441.341126896554,
 8504.739421094373,
 8723.786333109352,
 8716.636068786307,
 8510.229558491828,
 8368.682254089688,
 8094.176849034841,
 8250.823984370481,
 8247.034012253882,
 8513.099624982598,
 8418.841524328544,
 8041.637738020887,
 7557.6863255798535,
 7587.205823679988,
 7480.0080101862,
 7355.74995116884,
 7368.090065224858,
 7135.864186783813,
 7472.457850583138,
 7406.389193398243,
 7494.03754752532,
 7541.316985820902,
 7643.315184129213,
 7720.1136322523025,
 7514.337481916922,
 7633.624925610012,
 7653.844783291085,
 7678.104608672846,
 7624.785238003865,
 7531.846938255654,
 6785.900153689353,
 6906.797920500267,
 6582.243594819853,
 6349.78773997235,
 6675.232186648456,
 6456.466031392953,
 6550.044456552766,
 6499.155218739275,
 6734.700862758878,
 6769.820359597132,
 6776.43010612411,
 6729.621362639197,
 6083.582481272837,
 6162.371128616136,
 6173.120938731963,
 6249.06979248725,
 6093.5622854587655,
 6157.021125462107,
 5903.335665144672,
 6218.189966853383,
 6403.88688202374,
 6385.707027370644,
 6614.063345257187,
 6529.47450739945,
 6597.433267916393,
 6639.022865310823,
 6673.382121671681,
 6856.809057407605,
 6773.760231409665,
 6741.630916127977,
 6329.838385325631,
 6394.597007057185,
 6228.7000351102515,
 6237.939617996416,
 6276.009258035969,
 6359.527802299326,
 6741.630916127977,
 7320.910722817447,
 7370.649590326029,
 7466.727971326733,
 7353.999982080227,
 7419.1589873644225,
 7418.359196804388,
 7710.973656981682,
 8424.120727951933,
 8181.245623555846,
 7951.439624245161,
 8164.8655417991395,
 8192.0056873968,
 8218.314792986417,
 8180.335483382522,
 7780.302510484863,
 7624.775472551371,
 7567.016238901684,
 7434.258818297923,
 7032.725871895731,
 7068.355125354666,
 6951.677010570504,
 6753.000832477776,
 6305.688421284536,
 6568.113961592583,
 6184.60071642243,
 6295.618774935577,
 6322.578259661924,
 6297.458586187231,
 6199.600451467769,
 6308.408588079379,
 6334.618086053459,
 6580.51364490887,
 6423.646298619276,
 6505.954903317453,
 6308.418353531881,
 6488.645150482415,
 6376.597325002777,
 6534.7644530205835,
 6719.84126195697,
 6763.070478826734,
 6707.141290976198,
 6884.518528886218,
 7096.154438996308,
 7047.0356777216975,
 6978.106719498534,
 7037.4557688157865,
 7193.122940992704,
 7272.591752102869,
 7259.931819477361,
 7361.530122505655,
 6792.710091992659,
 6529.0545929417995,
 6466.955592199568,
 6225.870006974743,
 6300.74856713565,
 6329.588389741541,
 6321.088539882515,
 6351.687608756908,
 6517.194939148952,
 6512.594922747189,
 6543.084618553544,
 6517.0650586306565,
 6281.089246428276,
 6371.187264315851,
 6398.4270175290485,
 6519.554760746419,
 6734.831231549806,
 6721.861245807314,
 6710.511348635148,
 6595.293657272881,
 6446.356346688735,
 6494.885274632136,
 6676.632064264837,
 6644.0125232674745,
 6601.843346266963,
 6625.443027059489,
 6589.503720483571,
 6555.984293038013,
 6502.474984317839,
 6576.573773096342,
 6622.363003339893,
 6588.193685030229,
 6602.833563150815,
 6652.112477846484,
 6642.52280348807,
 6585.413460702489,
 6256.129726374641,
 6274.469246176171,
 6285.8792008812325,
 6290.819055030116,
 6596.423520127534,
 6595.993351944756,
 6544.314577296359,
 6476.595558638376,
 6465.295953546603,
 6489.075318665195,
 6482.2355957317595,
 6487.045569362347,
 6475.625849204782,
 6495.725103547436,
 6476.175644180727,
 6474.635632320929,
 6480.265415689183,
 6486.275563432448,
 6332.518025492586,
 6334.158133240546,
 6317.4982712696155,
 6377.667130324535,
 6388.32709827733,
 6361.14740259703,
 6376.017257124074,
 6419.546761658321,
 6460.895640648541,
 6530.024790648026,
 6453.606218627321,
 6385.507323866954,
 6409.10700465948,
 6411.156773139959,
 6371.157479685719,
 6359.377902603401,
 5738.248737482908,
 5647.930020368755,
 5575.451320160579,
 5554.231968415775,
 5623.440706853163,
 4871.404186105692,
 4451.791480938562,
 4602.088630783817,
 4365.862822997347,
 4347.033077480144,
 3880.6914614023162,
 4009.8991400210634,
 3779.063129607575,
 3820.652482865693,
 4257.344720325091,
 4278.7710996629685,
 4017.1975950858496,
 4214.597428536373,
 4139.804804357497,
 3894.062074833764,
 3956.82390566467,
 3753.9285638178153,
 3521.039611151783,
 3419.8768473051446,
 3476.0533452403306,
 3614.170534450625,
 3502.5941361905916,
 3424.5276440599255,
 3486.8886030655635,
 3313.6187144785054,
 3242.4275891829116,
 3236.704545743249,
 3252.781654336035,
 3545.8021132011613,
 3695.9937961593787,
 3745.884516454389,
 4134.368376948812,
 3896.4748740110604,
 4014.1117120947506,
 3998.9095880462764,
 4078.527078170807,
 3815.423327186393,
 3857.2294734900884,
 3654.768938415951,
 3923.8493904688044,
 3820.3412090671436,
 3865.884349907607,
 3742.634329724918,
 3843.4521289618715,
 3943.3397688478685,
 3836.6734401065833,
 3857.6493879477375,
 3845.1266599299042,
 4076.560560172918,
 4025.177190462751,
 4030.7767009282443,
 4035.22510867989,
 3678.859577333089,
 3687.3003462044685,
 3661.23635347269,
 3552.890366900807,
 3705.9867837061834,
 3630.61116201285,
 3654.9422751978864,
 3678.4989879993973,
 3657.7747446965195,
 3728.5024992708236,
 3600.950064851416,
 3575.9693049385855,
 3604.5134784699344,
 3585.059720537759,
 3600.8018741096757,
 3599.7022841577846,
 3602.3968166398067,

In [235]:
final['final'] = new
final['final'] = final['final'].shift(1)
final['final'][0] = initial_position
final.fillna(0)
# cl_price3 = cl_price2

# cl_price3["BTC-USD_percent_change_shift"] = cl_price3["BTC-USD_percent_change"].shift(-1)       # shift the percent change columnn up 1
# cl_price3["BTC-USD_percent_change_shift"] = cl_price3["BTC-USD_percent_change_shift"].fillna(0) # then change the NA at end to be 0
# cl_price3.rename({'BTC-USD_percent_change_shift': 'BTC_USD_percent_change_shift'}, axis=1, inplace=True)
# cl_price3
final

,BTC_USD,ETH_USD,BTC_USD_percent_change,ETH_USD_percent_change,BTC_USD_percent_change_shift,ETH_USD_percent_change_shift,final
Date,,,,,,,
2016-05-11,452.727997,9.996280,NaN,NaN,0.004502,0.006154,452.720000
2016-05-12,454.765991,10.057800,0.004502,0.006154,0.001988,0.044622,454.757958
2016-05-13,455.670013,10.506600,0.001988,0.044622,0.000002,-0.025403,455.661965
2016-05-14,455.670990,10.239700,0.000002,-0.025403,0.004163,-0.027086,455.662941
2016-05-15,457.567993,9.962350,0.004163,-0.027086,-0.007442,0.121352,457.559911
...,...,...,...,...,...,...,...
2021-05-06,56396.515625,3490.880371,-0.017893,-0.009056,0.017020,-0.001762,56395.519457
2021-05-07,57356.402344,3484.729004,0.017020,-0.001762,0.025235,0.119929,57355.389221
2021-05-08,58803.777344,3902.647705,0.025235,0.119929,-0.009718,0.006713,58802.738655
2021-05-09,58232.316406,3928.844727,-0.009718,0.006713,-0.040742,0.005968,58231.287811
2021-05-10,55859.796875,3952.293945,-0.040742,0.005968,NaN,NaN,55858.810187